// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Option from "@rescript/core/src/Core__Option.re.mjs";
import * as LangProvider from "../shared/LangProvider.re.mjs";
import * as LucideReact from "lucide-react";
import * as WaitForMessages from "../shared/i18n/WaitForMessages.re.mjs";
import * as SelectedLocation from "../organisms/SelectedLocation.re.mjs";
import * as ReactRouterDom from "react-router-dom";
import * as JsxRuntime from "react/jsx-runtime";
import * as RescriptRelay_Query from "rescript-relay/src/RescriptRelay_Query.re.mjs";
import * as UpdateLocationEventForm from "../organisms/UpdateLocationEventForm.re.mjs";
import * as UpdateEventPageQuery_graphql from "../../__generated__/UpdateEventPageQuery_graphql.re.mjs";

import { t } from '@lingui/macro'
;

var convertVariables = UpdateEventPageQuery_graphql.Internal.convertVariables;

var convertResponse = UpdateEventPageQuery_graphql.Internal.convertResponse;

RescriptRelay_Query.useQuery(convertVariables, UpdateEventPageQuery_graphql.node, convertResponse);

RescriptRelay_Query.useLoader(convertVariables, UpdateEventPageQuery_graphql.node, (function (prim) {
        return prim;
      }));

var usePreloaded = RescriptRelay_Query.usePreloaded(UpdateEventPageQuery_graphql.node, convertResponse, (function (prim) {
        return prim;
      }));

RescriptRelay_Query.$$fetch(UpdateEventPageQuery_graphql.node, convertResponse, convertVariables);

RescriptRelay_Query.fetchPromised(UpdateEventPageQuery_graphql.node, convertResponse, convertVariables);

RescriptRelay_Query.retain(UpdateEventPageQuery_graphql.node, convertVariables);

function UpdateEventPage(props) {
  var data = ReactRouterDom.useLoaderData();
  var query = usePreloaded(data.data);
  var navigate = ReactRouterDom.useNavigate();
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsx(WaitForMessages.make, {
                    children: (function () {
                        return JsxRuntime.jsxs(JsxRuntime.Fragment, {
                                    children: [
                                      JsxRuntime.jsx("div", {
                                            children: JsxRuntime.jsxs("div", {
                                                  children: [
                                                    JsxRuntime.jsxs(LangProvider.Router.Link.make, {
                                                          to: "/events/" + Core__Option.getOr(Core__Option.map(query.event, (function (e) {
                                                                      return e.id;
                                                                    })), ""),
                                                          children: [
                                                            JsxRuntime.jsx(LucideReact.ArrowLeft, {
                                                                  className: "w-5 h-5"
                                                                }),
                                                            t`Cancel`
                                                          ],
                                                          className: "inline-flex items-center gap-2 text-gray-600 dark:text-gray-400 hover:text-gray-900 dark:hover:text-gray-100 transition-colors font-medium"
                                                        }),
                                                    JsxRuntime.jsx("h1", {
                                                          children: t`Update Event`,
                                                          className: "text-lg font-bold"
                                                        }),
                                                    JsxRuntime.jsx("div", {
                                                          className: "w-20"
                                                        })
                                                  ],
                                                  className: "max-w-2xl mx-auto px-4 py-4 flex items-center justify-between"
                                                }),
                                            className: "bg-white dark:bg-[#1a1a1a] shadow-sm border-b border-gray-200 dark:border-gray-800 transition-colors"
                                          }),
                                      JsxRuntime.jsx("div", {
                                            children: Core__Option.getOr(Core__Option.flatMap(query.location, (function ($$location) {
                                                        return Core__Option.map(query.event, (function ($$event) {
                                                                      return JsxRuntime.jsxs(JsxRuntime.Fragment, {
                                                                                  children: [
                                                                                    JsxRuntime.jsx(SelectedLocation.make, {
                                                                                          location: $$location.fragmentRefs,
                                                                                          onNewLocation: (function ($$location) {
                                                                                              navigate("../update/" + $$event.id + "/" + $$location, undefined);
                                                                                            })
                                                                                        }),
                                                                                    JsxRuntime.jsx(UpdateLocationEventForm.make, {
                                                                                          event: $$event.fragmentRefs,
                                                                                          location: $$location.fragmentRefs,
                                                                                          query: query.fragmentRefs
                                                                                        })
                                                                                  ]
                                                                                });
                                                                    }));
                                                      })), t`Event or Location doesn't exist.`),
                                            className: "max-w-2xl mx-auto px-4 py-8 space-y-6"
                                          })
                                    ]
                                  });
                      })
                  }),
              className: "min-h-screen bg-gray-50 dark:bg-[#111111] w-full text-gray-900 dark:text-gray-100 transition-colors"
            });
}

var make = UpdateEventPage;

export {
  make ,
}
/*  Not a pure module */
