// Generated by ReScript, PLEASE EDIT WITH CARE

import * as LeagueNav from "../../components/organisms/LeagueNav.re.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import * as RescriptRelay_Query from "rescript-relay/src/RescriptRelay_Query.re.mjs";
import * as LeagueNavStoryQuery_graphql from "../../__generated__/LeagueNavStoryQuery_graphql.re.mjs";

var convertVariables = LeagueNavStoryQuery_graphql.Internal.convertVariables;

var convertResponse = LeagueNavStoryQuery_graphql.Internal.convertResponse;

var convertWrapRawResponse = LeagueNavStoryQuery_graphql.Internal.convertWrapRawResponse;

var use = RescriptRelay_Query.useQuery(convertVariables, LeagueNavStoryQuery_graphql.node, convertResponse);

var useLoader = RescriptRelay_Query.useLoader(convertVariables, LeagueNavStoryQuery_graphql.node, (function (prim) {
        return prim;
      }));

var usePreloaded = RescriptRelay_Query.usePreloaded(LeagueNavStoryQuery_graphql.node, convertResponse, (function (prim) {
        return prim;
      }));

var $$fetch = RescriptRelay_Query.$$fetch(LeagueNavStoryQuery_graphql.node, convertResponse, convertVariables);

var fetchPromised = RescriptRelay_Query.fetchPromised(LeagueNavStoryQuery_graphql.node, convertResponse, convertVariables);

var retain = RescriptRelay_Query.retain(LeagueNavStoryQuery_graphql.node, convertVariables);

var Query = {
  Operation: undefined,
  Types: undefined,
  convertVariables: convertVariables,
  convertResponse: convertResponse,
  convertWrapRawResponse: convertWrapRawResponse,
  use: use,
  useLoader: useLoader,
  usePreloaded: usePreloaded,
  $$fetch: $$fetch,
  fetchPromised: fetchPromised,
  retain: retain
};

function LeagueNavStory(props) {
  var data = use(undefined, undefined, undefined, undefined);
  return JsxRuntime.jsx(LeagueNav.make, {
              query: data.fragmentRefs
            });
}

var query = LeagueNavStoryQuery_graphql.node;

var make = LeagueNavStory;

export {
  Query ,
  query ,
  make ,
}
/* use Not a pure module */
