// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Core__Array from "@rescript/core/src/Core__Array.re.mjs";
import * as PrintableDraws from "../../components/organisms/PrintableDraws.re.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import * as StoryFixturesMatch from "./StoryFixturesMatch.re.mjs";

function toPrintable(rounds) {
  return rounds.map(function (round, roundIdx) {
              return {
                      roundNumber: roundIdx + 1 | 0,
                      matches: round.map(function (entity, matchIdx) {
                            var match = entity.match;
                            var team = function (players) {
                              return {
                                      players: players.map(function (p) {
                                            return {
                                                    id: p.id,
                                                    number: p.intId,
                                                    name: p.name
                                                  };
                                          })
                                    };
                            };
                            return {
                                    id: entity.id,
                                    courtNumber: matchIdx + 1 | 0,
                                    team1: team(match[0]),
                                    team2: team(match[1])
                                  };
                          })
                    };
            });
}

function longEvening(players) {
  var regulars = players.slice(0, 16);
  return Core__Array.fromInitializer(8, (function (r) {
                var order = Core__Array.fromInitializer(16, (function (i) {
                        return regulars[(Math.imul(i, 5) + Math.imul(r, 3) | 0) % 16];
                      }));
                return Core__Array.fromInitializer(3, (function (c) {
                              return StoryFixturesMatch.entity("long-r" + r.toString() + "-c" + c.toString(), undefined, [
                                          [
                                            order[(c << 2) + 0 | 0],
                                            order[(c << 2) + 3 | 0]
                                          ],
                                          [
                                            order[(c << 2) + 1 | 0],
                                            order[(c << 2) + 2 | 0]
                                          ]
                                        ]);
                            }));
              }));
}

function PrintableDrawsStory(props) {
  var __onClose = props.onClose;
  var __state = props.state;
  var state = __state !== undefined ? __state : "threeRounds";
  var onClose = __onClose !== undefined ? __onClose : (function () {
        
      });
  var players = React.useMemo((function () {
          return StoryFixturesMatch.plainPlayers();
        }), []);
  var rounds = state === "singleMatch" ? [[StoryFixturesMatch.entity("solo", undefined, StoryFixturesMatch.doubles(players, [
                  StoryFixturesMatch.kenji,
                  StoryFixturesMatch.mai
                ], [
                  StoryFixturesMatch.yuki,
                  StoryFixturesMatch.takumi
                ]))]] : (
      state === "empty" ? [] : (
          state === "longNames" ? [[
                StoryFixturesMatch.entity("ln-c1", undefined, StoryFixturesMatch.doubles(players, [
                          StoryFixturesMatch.alexandra,
                          StoryFixturesMatch.maximilian
                        ], [
                          StoryFixturesMatch.shinnosuke,
                          StoryFixturesMatch.yukiko
                        ])),
                StoryFixturesMatch.entity("ln-c2", undefined, StoryFixturesMatch.doubles(players, [
                          StoryFixturesMatch.kenji,
                          StoryFixturesMatch.yukiko
                        ], [
                          StoryFixturesMatch.alexandra,
                          StoryFixturesMatch.chris
                        ]))
              ]] : (
              state === "manyRounds" ? longEvening(players) : StoryFixturesMatch.rounds(players)
            )
        )
    );
  return JsxRuntime.jsx(PrintableDraws.make, {
              rounds: toPrintable(rounds),
              onClose: onClose
            });
}

var make = PrintableDrawsStory;

export {
  toPrintable ,
  longEvening ,
  make ,
}
/* react Not a pure module */
