// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Util from "../shared/Util.re.mjs";
import * as Lingui from "../../locales/Lingui.re.mjs";
import * as Router from "../shared/Router.re.mjs";
import * as RelayEnv from "../../entry/RelayEnv.re.mjs";
import * as Localized from "../shared/i18n/Localized.re.mjs";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Core__Option from "@rescript/core/src/Core__Option.re.mjs";
import * as ClubsListPage from "../pages/ClubsListPage.re.mjs";
import * as ReactRouterDom from "react-router-dom";
import * as ClubsListPageQuery_graphql from "../../__generated__/ClubsListPageQuery_graphql.re.mjs";

var LoaderArgs = {};

var loadMessages = Lingui.loadMessages({
      en: import("../../locales/src/components/pages/ClubsListPage.re/en"),
      ja: import("../../locales/src/components/pages/ClubsListPage.re/ja"),
      th: import("../../locales/src/components/pages/ClubsListPage.re/th"),
      zhTW: import("../../locales/src/components/pages/ClubsListPage.re/zh-TW"),
      zhCN: import("../../locales/src/components/pages/ClubsListPage.re/zh-CN"),
      ko: import("../../locales/src/components/pages/ClubsListPage.re/ko"),
      vi: import("../../locales/src/components/pages/ClubsListPage.re/vi")
    });

async function loader(param) {
  var params = param.params;
  var url = new URL(param.request.url);
  var activitySlug = Core__Option.getOr(params.activitySlug, "pickleball");
  var after = Router.SearchParams.get(url.searchParams, "after");
  var now = new Date();
  now.setMinutes(0);
  now.setSeconds(0);
  now.setMilliseconds(0);
  var afterDate = Util.Datetime.fromDate(now);
  var query = ClubsListPageQuery_graphql.load(RelayEnv.getRelayEnv(param.context, import.meta.env.SSR), {
        activitySlug: activitySlug,
        after: after,
        afterDate: Caml_option.some(afterDate),
        first: 20
      }, "store-or-network", undefined, undefined);
  if (import.meta.env.SSR) {
    await Localized.loadMessages(params.lang, loadMessages);
  }
  return ReactRouterDom.defer({
              data: query,
              i18nLoaders: import.meta.env.SSR ? undefined : Caml_option.some(Localized.loadMessages(params.lang, loadMessages))
            });
}

var Component = ClubsListPage.make;

export {
  Component ,
  LoaderArgs ,
  loadMessages ,
  loader ,
}
/* loadMessages Not a pure module */
