// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Core__Option from "@rescript/core/src/Core__Option.re.mjs";

var tokyoDefault = {
  lat: 35.658581,
  lng: 139.745438
};

var current = {
  contents: "Resolving"
};

var listeners = {
  contents: []
};

function emit() {
  listeners.contents.forEach(function (l) {
        l();
      });
}

var started = {
  contents: false
};

function start() {
  if (!(!started.contents && Core__Option.isSome((window == null) ? undefined : Caml_option.some(window)))) {
    return ;
  }
  started.contents = true;
  var match = navigator.geolocation;
  if (match == null) {
    current.contents = {
      TAG: "Resolved",
      location: tokyoDefault,
      granted: false
    };
    return emit();
  } else {
    navigator.geolocation.getCurrentPosition((function (pos) {
            current.contents = {
              TAG: "Resolved",
              location: {
                lat: pos.coords.latitude,
                lng: pos.coords.longitude
              },
              granted: true
            };
            emit();
          }), (function (_err) {
            current.contents = {
              TAG: "Resolved",
              location: tokyoDefault,
              granted: false
            };
            emit();
          }));
    return ;
  }
}

function subscribe(cb) {
  listeners.contents = listeners.contents.concat([cb]);
  start();
  return function () {
    listeners.contents = listeners.contents.filter(function (l) {
          return l !== cb;
        });
  };
}

function useStatus() {
  return React.useSyncExternalStore(subscribe, (function () {
                return current.contents;
              }), (function () {
                return "Resolving";
              }));
}

function use() {
  var match = useStatus();
  if (typeof match !== "object") {
    return tokyoDefault;
  } else {
    return match.location;
  }
}

export {
  tokyoDefault ,
  current ,
  listeners ,
  emit ,
  started ,
  start ,
  subscribe ,
  useStatus ,
  use ,
}
/* react Not a pure module */
