// Generated by ReScript, PLEASE EDIT WITH CARE

import * as MultipleContainersTsx from "./multipleContainers.tsx";

var Items = {};

var make = MultipleContainersTsx.MultipleContainers;

export {
  Items ,
  make ,
}
/* make Not a pure module */
