// Generated by ReScript, PLEASE EDIT WITH CARE

import * as EventTags from "../shared/EventTags.re.mjs";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Core from "@linaria/core";
import * as JsxRuntime from "react/jsx-runtime";

import { t } from '@lingui/macro'
;

var allLevel = "all level";

var levelTags = [allLevel].concat(EventTags.specificLevels);

function toggle(tags, tag) {
  if (!tags.includes(tag)) {
    if (tag === allLevel) {
      return tags.filter(function (t) {
                    return !EventTags.specificLevels.includes(t);
                  }).concat([tag]);
    } else {
      return tags.filter(function (t) {
                    return t !== allLevel;
                  }).concat([tag]);
    }
  }
  var rest = tags.filter(function (t) {
        return t !== tag;
      });
  if (rest.length === 0) {
    return [allLevel];
  } else {
    return rest;
  }
}

var legendClass = "text-xs font-semibold uppercase tracking-wide text-gray-500 dark:text-gray-400";

function pillClass(active) {
  return Core.cx("h-9 rounded-full border px-3.5 text-xs font-semibold transition-colors focus:outline-none focus-visible:ring-2 focus-visible:ring-[#94c93a]", active ? "border-gray-900 bg-gray-900 text-white dark:border-gray-100 dark:bg-gray-100 dark:text-gray-900" : "border-gray-200 bg-white text-gray-600 hover:border-gray-400 dark:border-[#45464d] dark:bg-[#1e1f23] dark:text-gray-300 dark:hover:border-gray-500");
}

function LevelTagPills(props) {
  var legend = props.legend;
  var onChange = props.onChange;
  var selected = props.selected;
  return JsxRuntime.jsxs("fieldset", {
              children: [
                legend !== undefined ? JsxRuntime.jsx("legend", {
                        children: Caml_option.valFromOption(legend),
                        className: legendClass
                      }) : null,
                JsxRuntime.jsx("div", {
                      children: levelTags.map(function (tag) {
                            var active = selected.includes(tag);
                            return JsxRuntime.jsx("button", {
                                        children: tag === allLevel ? t`All levels` : tag,
                                        "aria-pressed": active ? "true" : "false",
                                        className: pillClass(active),
                                        type: "button",
                                        onClick: (function (param) {
                                            onChange(toggle(selected, tag));
                                          })
                                      }, tag);
                          }),
                      className: "mt-2 flex flex-wrap gap-2"
                    })
              ]
            });
}

var make = LevelTagPills;

export {
  allLevel ,
  levelTags ,
  toggle ,
  legendClass ,
  pillClass ,
  make ,
}
/*  Not a pure module */
