// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as TimeWindow from "./TimeWindow.re.mjs";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Core__Array from "@rescript/core/src/Core__Array.re.mjs";
import * as CourtLabels from "./CourtLabels.re.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.re.mjs";
import * as LucideReact from "lucide-react";
import * as FramerMotion from "framer-motion";
import * as Belt_SetString from "rescript/lib/es6/belt_SetString.js";
import * as Caml_splice_call from "rescript/lib/es6/caml_splice_call.js";
import * as CourtOpeningCard from "./CourtOpeningCard.re.mjs";
import * as JsxRuntime from "react/jsx-runtime";

import { t, plural } from '@lingui/macro'
;

function ts(prim0, prim1) {
  return Caml_splice_call.spliceApply(t, [
              prim0,
              prim1
            ]);
}

function countLocations(courts) {
  return Belt_SetString.size(Belt_SetString.fromArray(courts.map(function (c) {
                      return c.location.id;
                    })));
}

function CourtAvailabilityGroups(props) {
  var __defaultExpanded = props.defaultExpanded;
  var defaultExpanded = __defaultExpanded !== undefined ? __defaultExpanded : false;
  var match = React.useState(function () {
        return defaultExpanded;
      });
  var setExpanded = match[1];
  var expanded = match[0];
  var courts = TimeWindow.mergeCourtAvailabilityByCourt(props.courtAvailability).filter(function (court) {
          return court.intents.length > 0;
        }).toSorted(function (a, b) {
        var aStart = Core__Option.getOr(Core__Option.map(a.intents[0], (function (i) {
                    return i.start;
                  })), 0.0);
        var bStart = Core__Option.getOr(Core__Option.map(b.intents[0], (function (i) {
                    return i.start;
                  })), 0.0);
        if (aStart !== bStart) {
          return aStart - bStart;
        }
        var byLocation = a.location.name.localeCompare(b.location.name);
        if (byLocation !== 0.0) {
          return byLocation;
        } else {
          return Core__Option.getOr(a.courtName, "").localeCompare(Core__Option.getOr(b.courtName, ""));
        }
      });
  var locationCount = countLocations(courts);
  var openingCount = Core__Array.reduce(courts, 0, (function (total, court) {
          return total + court.intents.length | 0;
        }));
  if (courts.length === 0) {
    return null;
  }
  var summary = TimeWindow.summarizeCourtAvailability(undefined, undefined, courts);
  var surfaceLabel = CourtLabels.surfaceMix(summary, (function (n) {
          return t`${n} indoor`;
        }), (function (n) {
          return t`${n} outdoor`;
        }));
  var priceLabel = CourtLabels.priceRange(summary);
  var courtsPhrase = plural(summary.courtCount, {
        one: t`${summary.courtCount.toString()} court`,
        other: t`${summary.courtCount.toString()} courts`
      });
  var openingsPhrase = plural(openingCount, {
        one: t`${openingCount.toString()} continuous opening`,
        other: t`${openingCount.toString()} continuous openings`
      });
  var locationsPhrase = plural(locationCount, {
        one: t`${locationCount.toString()} location`,
        other: t`${locationCount.toString()} locations`
      });
  return JsxRuntime.jsxs("section", {
              children: [
                JsxRuntime.jsxs("button", {
                      children: [
                        JsxRuntime.jsxs("span", {
                              children: [
                                JsxRuntime.jsx("span", {
                                      children: JsxRuntime.jsx(LucideReact.MapPin, {
                                            size: 12,
                                            strokeWidth: 2.5
                                          }),
                                      className: "flex h-6 w-6 flex-shrink-0 items-center justify-center rounded-md bg-cyan-100 dark:bg-cyan-900/50"
                                    }),
                                JsxRuntime.jsxs("span", {
                                      children: [
                                        Core__Option.getOr(Core__Option.map(props.title, (function (tl) {
                                                    return JsxRuntime.jsx("span", {
                                                                children: tl,
                                                                className: "block truncate text-xs font-semibold text-gray-900 dark:text-gray-100"
                                                              });
                                                  })), null),
                                        JsxRuntime.jsx("span", {
                                              children: courtsPhrase + " · " + openingsPhrase + " · " + locationsPhrase + Core__Option.getOr(Core__Option.map(surfaceLabel, (function (s) {
                                                          return " · " + s;
                                                        })), "") + Core__Option.getOr(Core__Option.map(priceLabel, (function (p) {
                                                          return " · " + p;
                                                        })), ""),
                                              className: "block font-mono text-[9px] text-cyan-700 dark:text-cyan-400"
                                            })
                                      ],
                                      className: "min-w-0"
                                    })
                              ],
                              className: "flex min-w-0 items-center gap-2"
                            }),
                        JsxRuntime.jsx(LucideReact.ChevronDown, {
                              size: 14,
                              className: "flex-shrink-0 transition-transform " + (
                                expanded ? "rotate-180" : ""
                              )
                            })
                      ],
                      "aria-expanded": expanded,
                      className: "flex w-full items-center justify-between gap-3 px-2.5 py-2 text-left text-cyan-800 transition-colors hover:bg-cyan-100/70 focus:outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-cyan-500 dark:text-cyan-300 dark:hover:bg-cyan-900/20",
                      type: "button",
                      onClick: (function (param) {
                          setExpanded(function (v) {
                                return !v;
                              });
                        })
                    }),
                expanded ? JsxRuntime.jsx(FramerMotion.motion.div, {
                        className: "overflow-hidden",
                        animate: {
                          height: "auto",
                          opacity: 1
                        },
                        initial: {
                          height: "0px",
                          opacity: 0
                        },
                        exit: {
                          height: "0px",
                          opacity: 0
                        },
                        transition: {
                          duration: 0.18
                        },
                        children: Caml_option.some(JsxRuntime.jsx("div", {
                                  children: courts.map(function (court) {
                                        return JsxRuntime.jsx(CourtOpeningCard.make, {
                                                    court: court,
                                                    spans: court.intents,
                                                    className: "bg-white/80 px-2.5 py-2.5 dark:bg-[#1e1f23]/80"
                                                  }, court.id);
                                      }),
                                  className: "divide-y divide-cyan-100 border-t border-cyan-200/70 dark:divide-cyan-900/40 dark:border-cyan-800/40"
                                }))
                      }) : null
              ],
              className: "overflow-hidden rounded-md border border-cyan-200 bg-cyan-50/70 dark:border-cyan-800/50 dark:bg-cyan-950/20"
            });
}

var make = CourtAvailabilityGroups;

export {
  ts ,
  countLocations ,
  make ,
}
/*  Not a pure module */
