// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Util from "../shared/Util.re.mjs";
import * as React from "react";
import * as Layout from "../shared/Layout.re.mjs";
import * as Rating from "../../lib/Rating.re.mjs";
import * as Session from "../../lib/Session.re.mjs";
import * as Caml_obj from "rescript/lib/es6/caml_obj.js";
import * as UiAction from "../atoms/UiAction.re.mjs";
import * as CompMatch from "./CompMatch.re.mjs";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Core__Array from "@rescript/core/src/Core__Array.re.mjs";
import * as MatchesView from "./MatchesView.re.mjs";
import * as SelectMatch from "./SelectMatch.re.mjs";
import * as SubmitMatch from "./SubmitMatch.re.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.re.mjs";
import * as RelayRuntime from "relay-runtime";
import * as SessionAddPlayer from "./SessionAddPlayer.re.mjs";
import * as React$1 from "@headlessui/react";
import * as SelectPlayersList from "./SelectPlayersList.re.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import * as ReactHelmetAsync from "react-helmet-async";
import * as SessionEvenPlayMode from "./SessionEvenPlayMode.re.mjs";
import * as AppContext from "../layouts/appContext";
import * as AiTetsu_event_graphql from "../../__generated__/AiTetsu_event_graphql.re.mjs";
import * as RescriptRelay_Fragment from "rescript-relay/src/RescriptRelay_Fragment.re.mjs";
import * as RescriptRelay_Mutation from "rescript-relay/src/RescriptRelay_Mutation.re.mjs";
import * as Solid from "@heroicons/react/24/solid";
import * as Outline from "@heroicons/react/24/outline";
import * as AiTetsuRsvpsRefetchQuery_graphql from "../../__generated__/AiTetsuRsvpsRefetchQuery_graphql.re.mjs";
import * as AiTetsuSubmitMatchMutation_graphql from "../../__generated__/AiTetsuSubmitMatchMutation_graphql.re.mjs";
import * as AiTetsuCreateRatingMutation_graphql from "../../__generated__/AiTetsuCreateRatingMutation_graphql.re.mjs";

import { css, cx } from '@linaria/core'
;

import { t, plural } from '@lingui/macro'
;

var convertVariables = AiTetsuCreateRatingMutation_graphql.Internal.convertVariables;

var convertResponse = AiTetsuCreateRatingMutation_graphql.Internal.convertResponse;

var convertWrapRawResponse = AiTetsuCreateRatingMutation_graphql.Internal.convertWrapRawResponse;

RescriptRelay_Mutation.commitMutation(convertVariables, AiTetsuCreateRatingMutation_graphql.node, convertResponse, convertWrapRawResponse);

var use = RescriptRelay_Mutation.useMutation(convertVariables, AiTetsuCreateRatingMutation_graphql.node, convertResponse, convertWrapRawResponse);

var convertVariables$1 = AiTetsuSubmitMatchMutation_graphql.Internal.convertVariables;

var convertResponse$1 = AiTetsuSubmitMatchMutation_graphql.Internal.convertResponse;

var convertWrapRawResponse$1 = AiTetsuSubmitMatchMutation_graphql.Internal.convertWrapRawResponse;

RescriptRelay_Mutation.commitMutation(convertVariables$1, AiTetsuSubmitMatchMutation_graphql.node, convertResponse$1, convertWrapRawResponse$1);

var use$1 = RescriptRelay_Mutation.useMutation(convertVariables$1, AiTetsuSubmitMatchMutation_graphql.node, convertResponse$1, convertWrapRawResponse$1);

var getConnectionNodes = AiTetsu_event_graphql.Utils.getConnectionNodes;

var convertFragment = AiTetsu_event_graphql.Internal.convertFragment;

function use$2(fRef) {
  return RescriptRelay_Fragment.useFragment(AiTetsu_event_graphql.node, convertFragment, fRef);
}

var convertRefetchVariables = AiTetsuRsvpsRefetchQuery_graphql.Internal.convertVariables;

function usePagination(fRef) {
  return RescriptRelay_Fragment.usePaginationFragment(AiTetsu_event_graphql.node, fRef, convertFragment, convertRefetchVariables);
}

function AiTetsu$TeamListItem(props) {
  var onDelete = props.onDelete;
  var id = props.id;
  return JsxRuntime.jsxs(JsxRuntime.Fragment, {
              children: [
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx(UiAction.make, {
                              onClick: (function (param) {
                                  onDelete(id);
                                }),
                              children: JsxRuntime.jsx(Outline.XMarkIcon, {
                                    className: "h-8 w-8 inline"
                                  })
                            }),
                        t`Team ${id.toString()}`
                      ],
                      className: "text-xl"
                    }),
                props.team.map(function (player) {
                      return JsxRuntime.jsx(CompMatch.PlayerMini.make, {
                                  player: player
                                });
                    })
              ]
            });
}

function AiTetsu$TeamsList(props) {
  var onDelete = props.onDelete;
  return JsxRuntime.jsx("ul", {
              children: Util.NonEmptyArray.toArray(Util.NonEmptyArray.mapWithIndex(props.teams, (function (team, i) {
                          return JsxRuntime.jsx("li", {
                                      children: JsxRuntime.jsx(AiTetsu$TeamListItem, {
                                            id: i + 1 | 0,
                                            team: team,
                                            onDelete: (function (param) {
                                                onDelete(i);
                                              })
                                          })
                                    }, i.toString());
                        })))
            });
}

function AiTetsu$TeamSelector(props) {
  var onTeamCreate = props.onTeamCreate;
  var players = props.players;
  var maxRating = Core__Array.reduce(players, 0, (function (acc, next) {
          if (next.rating.mu > acc) {
            return next.rating.mu;
          } else {
            return acc;
          }
        }));
  var minRating = Core__Array.reduce(players, maxRating, (function (acc, next) {
          if (next.rating.mu < acc) {
            return next.rating.mu;
          } else {
            return acc;
          }
        }));
  var match = React.useState(function () {
        return [];
      });
  var setMembers = match[1];
  var members = match[0];
  var onSelectPlayer = function (player) {
    setMembers(function (param) {
          var removed = members.filter(function (p) {
                return p.id !== player.id;
              });
          if (removed.length < members.length) {
            return removed;
          } else {
            return members.concat([player]);
          }
        });
  };
  return JsxRuntime.jsxs(JsxRuntime.Fragment, {
              children: [
                JsxRuntime.jsx(SelectMatch.SelectEventPlayersList.make, {
                      players: players,
                      selected: members,
                      disabled: props.teamPlayers,
                      onSelectPlayer: onSelectPlayer,
                      minRating: minRating,
                      maxRating: maxRating
                    }),
                JsxRuntime.jsx("div", {
                      children: JsxRuntime.jsx(UiAction.make, {
                            onClick: (function (param) {
                                var match = members.length;
                                if (!(match === 0 || match === 1)) {
                                  onTeamCreate(members);
                                  return setMembers(function (param) {
                                              return [];
                                            });
                                }
                                
                              }),
                            className: "rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600",
                            children: t`Create Team`
                          }),
                      className: "mt-6 flex items-center justify-end gap-x-6"
                    })
              ]
            });
}

function AiTetsu$Checkin(props) {
  var onToggleCheckin = props.onToggleCheckin;
  var disabled = props.disabled;
  var players = props.players;
  var maxRating = Core__Array.reduce(players, 0, (function (acc, next) {
          if (next.rating.mu > acc) {
            return next.rating.mu;
          } else {
            return acc;
          }
        }));
  var minRating = Core__Array.reduce(players, maxRating, (function (acc, next) {
          if (next.rating.mu < acc) {
            return next.rating.mu;
          } else {
            return acc;
          }
        }));
  return JsxRuntime.jsx("div", {
              children: players.map(function (player) {
                    var match = disabled.has(player.id);
                    var match$1 = player.paid;
                    var status = match ? "Available" : (
                        match$1 ? "Queued" : "Break"
                      );
                    return JsxRuntime.jsx(UiAction.make, {
                                onClick: (function (param) {
                                    onToggleCheckin(player, disabled.has(player.id));
                                  }),
                                children: JsxRuntime.jsx(MatchesView.PlayerView.make, {
                                      player: player,
                                      minRating: minRating,
                                      maxRating: maxRating,
                                      status: status
                                    }, player.id)
                              });
                  }),
              className: "grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-3"
            });
}

function getDeprioritizedPlayers(history, players, session, $$break) {
  var lastPlayed = Rating.CompletedMatches.getLastPlayedPlayers(history, $$break, players.length);
  var maxCount = Core__Array.reduce(players, 0, (function (acc, next) {
          var count = Session.get(session, next.id).count;
          if (count > acc) {
            return count;
          } else {
            return acc;
          }
        }));
  var minCount = Core__Array.reduce(players, maxCount, (function (acc, next) {
          var count = Session.get(session, next.id).count;
          if (count < acc) {
            return count;
          } else {
            return acc;
          }
        }));
  var breakPlayers = Rating.Players.sortByPlayCountDesc(players.filter(function (p) {
              var count = Session.get(session, p.id).count;
              if (count === maxCount) {
                return count !== minCount;
              } else {
                return false;
              }
            }), session).slice(0, $$break);
  if (breakPlayers.length >= $$break) {
    return new Set(breakPlayers.map(function (p) {
                    return p.id;
                  }));
  }
  var breakAndLastPlayed = Rating.Players.addBreakPlayersFrom(breakPlayers, lastPlayed, $$break);
  if (breakAndLastPlayed.length < $$break) {
    return new Set(Rating.Players.addBreakPlayersFrom(breakAndLastPlayed, players, $$break).map(function (p) {
                    return p.id;
                  }));
  } else {
    return new Set(breakAndLastPlayed.map(function (p) {
                    return p.id;
                  }));
  }
}

function getPriorityPlayers(history, players, session, $$break) {
  var lastPlayed = Rating.CompletedMatches.getLastPlayedPlayers(history, $$break, players.length);
  var maxCount = Core__Array.reduce(players, 0, (function (acc, next) {
          var count = Session.get(session, next.id).count;
          if (count > acc) {
            return count;
          } else {
            return acc;
          }
        }));
  var minCount = Core__Array.reduce(players, maxCount, (function (acc, next) {
          var count = Session.get(session, next.id).count;
          if (count < acc) {
            return count;
          } else {
            return acc;
          }
        }));
  var breakPlayers = Rating.Players.sortByPlayCountDesc(players.filter(function (p) {
                var count = Session.get(session, p.id).count;
                if (count === maxCount) {
                  return count !== minCount;
                } else {
                  return false;
                }
              }), session).slice(0, $$break).map(function (p) {
        return p.id;
      });
  var deprioritized = breakPlayers.length < $$break ? new Set(Rating.Players.filterOut(lastPlayed, new Set(breakPlayers)).slice(0, $$break - breakPlayers.length | 0).map(function (p) {
                return p.id;
              }).concat(breakPlayers)) : new Set(breakPlayers);
  return {
          prioritized: Core__Array.reduce(players, [], (function (acc, next) {
                  var count = Session.get(session, next.id).count;
                  if (minCount !== maxCount && count === minCount) {
                    return acc.concat([next]);
                  } else {
                    return acc;
                  }
                })),
          deprioritized: deprioritized
        };
}

function rsvpToPlayer(rsvp) {
  var match = Core__Option.map(rsvp.user, (function (u) {
          return u.id;
        }));
  var match$1 = rsvp.rating;
  if (match === undefined) {
    return ;
  }
  var rating;
  if (match$1 !== undefined) {
    var mu = match$1.mu;
    if (mu !== undefined) {
      var sigma = match$1.sigma;
      rating = sigma !== undefined ? Rating.Rating.make(mu, sigma) : Rating.Rating.makeDefault();
    } else {
      rating = Rating.Rating.makeDefault();
    }
  } else {
    rating = Rating.Rating.makeDefault();
  }
  return {
          data: rsvp,
          id: match,
          name: Core__Option.getOr(Core__Option.flatMap(rsvp.user, (function (u) {
                      return u.lineUsername;
                    })), ""),
          rating: rating,
          ratingOrdinal: Rating.Rating.ordinal(rating),
          paid: false
        };
}

function addToQueue(queue, player) {
  var newSet = new Set();
  queue.forEach(function (id) {
        newSet.add(id);
      });
  newSet.add(player.id);
  return newSet;
}

function removeFromQueue(queue, player) {
  var newSet = new Set();
  queue.forEach(function (id) {
        newSet.add(id);
      });
  newSet.delete(player.id);
  return newSet;
}

function AiTetsu(props) {
  var $$event = props.event;
  var match = use$2($$event);
  var eventId = match.id;
  var activity = match.activity;
  var match$1 = use();
  var commitMutationCreateRating = match$1[0];
  var match$2 = use$1();
  var commitMutationCreateLeagueMatch = match$2[0];
  var match$3 = React.useState(function () {
        return [];
      });
  var setMatches = match$3[1];
  var matches = match$3[0];
  var match$4 = React.useState(function () {
        return false;
      });
  var setManualTeamOpen = match$4[1];
  var match$5 = React.useState(function () {
        return "Advanced";
      });
  var setScreen = match$5[1];
  var match$6 = React.useState(function () {
        return Util.NonEmptyArray.empty;
      });
  var setTeams = match$6[1];
  var teams = match$6[0];
  var match$7 = React.useState(function () {
        
      });
  var setSettingsPane = match$7[1];
  var settingsPane = match$7[0];
  var match$8 = React.useState(function () {
        return new Set();
      });
  var setQueue = match$8[1];
  var match$9 = React.useState(function () {
        return new Set();
      });
  var setDisabled = match$9[1];
  var disabled = match$9[0];
  var match$10 = React.useState(function () {
        return Session.make();
      });
  var setSessionState = match$10[1];
  var sessionState = match$10[0];
  var match$11 = React.useState(function () {
        return [];
      });
  var setSessionPlayers = match$11[1];
  var sessionPlayers = match$11[0];
  var match$12 = React.useState(function () {
        return false;
      });
  var setSessionMode = match$12[1];
  var sessionMode = match$12[0];
  var match$13 = React.useState(function () {
        return 0;
      });
  var setBreakCount = match$13[1];
  var breakCount = match$13[0];
  var match$14 = React.useState(function () {
        return [];
      });
  var setMatchHistory = match$14[1];
  var matchHistory = match$14[0];
  var toggleQueuePlayer = function (player) {
    setQueue(function (queue) {
          var newSet = new Set();
          queue.forEach(function (id) {
                newSet.add(id);
              });
          if (queue.has(player.id)) {
            return removeFromQueue(newSet, player);
          } else {
            return addToQueue(newSet, player);
          }
        });
  };
  var match$15 = usePagination($$event);
  var data = match$15.data;
  var allPlayers = sessionMode || sessionPlayers.length >= getConnectionNodes(data.rsvps).length ? sessionPlayers : Core__Array.filterMap(getConnectionNodes(data.rsvps), rsvpToPlayer).concat(sessionPlayers);
  var players = allPlayers.filter(function (p) {
        return !disabled.has(p.id);
      });
  var seenTeams = new Set(matchHistory.flatMap(function (param) {
              var match = param[0];
              return [
                      match[0],
                      match[1]
                    ];
            }).map(function (t) {
            return Rating.Team.toStableId(t);
          }));
  var lastRoundSeenTeams = new Set(Rating.CompletedMatches.getlastRoundMatches(matchHistory, breakCount, players.length, 4).flatMap(function (param) {
              var match = param[0];
              return [
                      match[0],
                      match[1]
                    ];
            }).map(function (t) {
            return Rating.Team.toStableId(t);
          }));
  var initializeRatings = function () {
    return allPlayers.map(function (p) {
                commitMutationCreateRating({
                      userId: p.id
                    }, undefined, undefined, undefined, undefined, undefined, undefined);
              });
  };
  var clearSession = function () {
    Session.saveState(Session.make(), eventId);
    Rating.Players.savePlayers([], eventId);
    Rating.CompletedMatches.saveMatches([], eventId);
  };
  React.useEffect((function () {
          console.log("Initializing player ratings");
          initializeRatings();
          console.log("Loading state");
          var state = Session.loadState(eventId);
          var players = Rating.Players.loadPlayers(allPlayers, eventId);
          var history = Rating.CompletedMatches.loadMatches(eventId, allPlayers);
          setSessionState(function (param) {
                return state;
              });
          setSessionPlayers(function (param) {
                return players;
              });
          setMatchHistory(function (param) {
                return history;
              });
          console.log("Disabling players by default");
          setDisabled(function (param) {
                return new Set(allPlayers.map(function (p) {
                                return p.id;
                              }));
              });
        }), []);
  React.useEffect((function () {
          var history = Rating.CompletedMatches.loadMatches(eventId, allPlayers);
          setMatchHistory(function (param) {
                return history;
              });
        }), [sessionPlayers]);
  var consumedPlayers = new Set(matches.flatMap(function (match) {
            return match[0].concat(match[1]).map(function (p) {
                        return p.id;
                      });
          }));
  var availablePlayers = players.filter(function (p) {
        return !consumedPlayers.has(p.id);
      });
  var deprioritized = getDeprioritizedPlayers(matchHistory, players, sessionState, breakCount);
  var queue = match$8[0].difference(disabled);
  var breakPlayersCount = queue.size;
  var queue$1 = queue.difference(deprioritized);
  var queuedPlayers = players.filter(function (p) {
        return queue$1.has(p.id);
      });
  var match$16 = getPriorityPlayers(matchHistory, queuedPlayers, sessionState, breakCount);
  var priorityPlayers = match$16.prioritized;
  var availablePlayers$1 = availablePlayers.filter(function (p) {
        return !deprioritized.has(p.id);
      });
  var incompatiblePlayers = new Set([
        "User_7e5631a2-53a9-11ef-b5a9-2b281b5a76b0",
        "User_55448d42-0843-11ef-8202-7b71b4052443"
      ]);
  var avoidAllPlayers = queuedPlayers.filter(function (p) {
        return incompatiblePlayers.has(p.id);
      });
  var maxRating = Core__Array.reduce(players, 0, (function (acc, next) {
          if (next.rating.mu > acc) {
            return next.rating.mu;
          } else {
            return acc;
          }
        }));
  var minRating = Core__Array.reduce(players, maxRating, (function (acc, next) {
          if (next.rating.mu < acc) {
            return next.rating.mu;
          } else {
            return acc;
          }
        }));
  var queueMatch = function (match) {
    var matches$1 = matches.concat([match]);
    [
          match[0],
          match[1]
        ].flatMap(function (x) {
            return x;
          }).map(function (p) {
          setQueue(function (queue) {
                return removeFromQueue(queue, p);
              });
        });
    setMatches(function (param) {
          return matches$1;
        });
  };
  var dequeueMatch = function (index) {
    var matches$1 = matches.filter(function (param, i) {
          return i !== index;
        });
    setMatches(function (param) {
          return matches$1;
        });
  };
  var updatePlayCounts = function (match) {
    setSessionState(function (prevState) {
          var nextState = Core__Array.reduce([
                  match[0],
                  match[1]
                ].flatMap(function (x) {
                    return x;
                  }), prevState, (function (state, p) {
                  return Session.update(state, p.id, (function (prev) {
                                return {
                                        count: prev.count + 1 | 0,
                                        paid: prev.paid
                                      };
                              }));
                }));
          Session.saveState(nextState, eventId);
          return nextState;
        });
  };
  var initializeSessionMode = function () {
    if (sessionPlayers.length >= getConnectionNodes(data.rsvps).length) {
      return ;
    }
    var players = Core__Array.filterMap(getConnectionNodes(data.rsvps), rsvpToPlayer).concat(sessionPlayers);
    setSessionPlayers(function (param) {
          return players;
        });
  };
  var uninitializeSessionMode = function () {
    setSessionPlayers(function (param) {
          return players.filter(function (p) {
                      return Core__Option.isNone(p.data);
                    });
        });
  };
  var updateSessionPlayerRatings = function (updatedPlayers) {
    setSessionPlayers(function (players) {
          var newState = players.map(function (p) {
                var player = updatedPlayers.find(function (p$p) {
                      return p.id === p$p.id;
                    });
                if (player !== undefined) {
                  return player;
                } else {
                  return p;
                }
              });
          Rating.Players.savePlayers(newState, eventId);
          return newState;
        });
  };
  var submitMatch = function (match, score, activitySlug) {
    var connectionId = RelayRuntime.ConnectionHandler.getConnectionID("root", "MatchListFragment_matches", {
          activitySlug: activitySlug,
          after: undefined,
          before: undefined,
          eventId: undefined,
          first: undefined,
          namespace: "doubles:rec"
        });
    return new Promise((function (resolve, reject) {
                  commitMutationCreateLeagueMatch({
                        connections: [connectionId],
                        matchInput: {
                          activitySlug: activitySlug,
                          doublesMatch: {
                            createdAt: Util.Datetime.fromDate(new Date()),
                            losers: match[1].map(function (p) {
                                  return p.id;
                                }),
                            score: [
                              score[0],
                              score[1]
                            ],
                            winners: match[0].map(function (p) {
                                  return p.id;
                                })
                          },
                          namespace: "doubles:rec"
                        }
                      }, undefined, undefined, undefined, (function (param, errs) {
                          if (errs !== undefined) {
                            console.log(errs);
                            return ;
                          } else {
                            return resolve();
                          }
                        }), (function (e) {
                          reject(e);
                        }), undefined);
                }));
  };
  var handleMatchComplete = function (completedMatch, matchId) {
    var score = completedMatch[1];
    var match = completedMatch[0];
    if (matchId > -1) {
      dequeueMatch(matchId);
    }
    updatePlayCounts(match);
    var rated_match = Rating.Match.rate(match);
    updateSessionPlayerRatings(rated_match.flatMap(function (x) {
              return x;
            }));
    setMatchHistory(function (matches) {
          var matches$1 = matches.concat([completedMatch]);
          Rating.CompletedMatches.saveMatches(matches$1, eventId);
          return matches$1;
        });
    if (sessionMode) {
      return Promise.resolve();
    } else {
      return Core__Option.getOr(Core__Option.flatMap(activity, (function (activity) {
                        return Core__Option.map(activity.slug, (function (slug) {
                                      return Rating.CompletedMatch.submit([
                                                  match,
                                                  score
                                                ], slug, submitMatch);
                                    }));
                      })), Promise.resolve());
    }
  };
  var breakPlayersDesc = plural(breakPlayersCount, {
        one: "player",
        other: "players"
      });
  var createTeam = function (team) {
    setTeams(function (teams) {
          return Util.NonEmptyArray.concat(teams, Util.NonEmptyArray.pure(team));
        });
  };
  var onDeleteTeam = function (i) {
    setTeams(function (teams) {
          return Util.NonEmptyArray.filterWithIndex(teams, (function (param, i$p) {
                        return i$p !== i;
                      }));
        });
  };
  var selectAllPlayers = function () {
    if (queue$1.size === availablePlayers$1.length) {
      return setQueue(function (param) {
                  return new Set();
                });
    } else {
      return setQueue(function (param) {
                  return new Set(availablePlayers$1.map(function (p) {
                                  return p.id;
                                }));
                });
    }
  };
  if (match$5[0] !== "Advanced") {
    return Core__Option.getOr(Core__Option.map(activity, (function (activity) {
                      return JsxRuntime.jsx(MatchesView.make, {
                                  players: players,
                                  checkin: JsxRuntime.jsx(AiTetsu$Checkin, {
                                        players: allPlayers,
                                        disabled: disabled,
                                        onToggleCheckin: (function (player, status) {
                                            if (status) {
                                              return setDisabled(function (disabled) {
                                                          return removeFromQueue(disabled, player);
                                                        });
                                            } else {
                                              return setDisabled(function (disabled) {
                                                          return addToQueue(disabled, player);
                                                        });
                                            }
                                          }),
                                        onUpdatePlayer: (function (p, paid) {
                                            var playerId = p.id;
                                            setSessionState(function (prevState) {
                                                  var nextState = Session.update(prevState, playerId, (function (prev) {
                                                          return {
                                                                  count: prev.count,
                                                                  paid: paid
                                                                };
                                                        }));
                                                  Session.saveState(nextState, eventId);
                                                  return nextState;
                                                });
                                          })
                                      }),
                                  queue: queue$1,
                                  breakPlayers: deprioritized,
                                  consumedPlayers: consumedPlayers,
                                  togglePlayer: toggleQueuePlayer,
                                  matches: matches,
                                  activity: activity,
                                  minRating: minRating,
                                  maxRating: maxRating,
                                  handleMatchCanceled: dequeueMatch,
                                  handleMatchComplete: handleMatchComplete,
                                  onClose: (function (param) {
                                      setScreen(function (param) {
                                            return "Advanced";
                                          });
                                    }),
                                  selectAll: selectAllPlayers,
                                  breakCount: breakCount,
                                  onChangeBreakCount: (function (numberOnBreak) {
                                      setBreakCount(function (param) {
                                            return Math.max(0, numberOnBreak);
                                          });
                                      setSettingsPane(function (param) {
                                            
                                          });
                                    }),
                                  matchSelector: JsxRuntime.jsx(CompMatch.make, {
                                        players: queuedPlayers,
                                        teams: teams,
                                        consumedPlayers: new Set(),
                                        seenTeams: seenTeams,
                                        lastRoundSeenTeams: lastRoundSeenTeams,
                                        priorityPlayers: priorityPlayers,
                                        avoidAllPlayers: avoidAllPlayers,
                                        onSelectMatch: (function (match) {
                                            queueMatch(match);
                                          })
                                      })
                                });
                    })), null);
  }
  var tmp;
  if (settingsPane !== undefined) {
    switch (settingsPane) {
      case "TeamBuilder" :
          tmp = JsxRuntime.jsxs(JsxRuntime.Fragment, {
                children: [
                  JsxRuntime.jsx("p", {
                        children: t`Players in teams will always be placed in a match together on the same side.`,
                        className: "mt-2 text-base leading-7 text-gray-600"
                      }),
                  JsxRuntime.jsx(AiTetsu$TeamsList, {
                        teams: teams,
                        onDelete: onDeleteTeam
                      }),
                  JsxRuntime.jsx(AiTetsu$TeamSelector, {
                        players: players,
                        onTeamCreate: createTeam,
                        teamPlayers: Util.NonEmptyArray.toArray(teams).flatMap(function (x) {
                              return x;
                            })
                      })
                ]
              });
          break;
      case "AddPlayer" :
          tmp = JsxRuntime.jsx(SessionAddPlayer.make, {
                eventId: eventId,
                onPlayerAdd: (function (player) {
                    setSessionPlayers(function (guests) {
                          var player$1 = Rating.Player.makeDefaultRatingPlayer(player.name);
                          var newState = guests.concat([player$1]);
                          Rating.Players.savePlayers(newState, eventId);
                          return newState;
                        });
                    setSettingsPane(function (param) {
                          
                        });
                  })
              });
          break;
      case "Settings" :
          tmp = JsxRuntime.jsxs("div", {
                children: [
                  JsxRuntime.jsx(SessionEvenPlayMode.make, {
                        breakCount: breakCount,
                        breakPlayersCount: breakPlayersCount,
                        onChangeBreakCount: (function (numberOnBreak) {
                            setBreakCount(function (param) {
                                  return Math.max(0, numberOnBreak);
                                });
                            setSettingsPane(function (param) {
                                  
                                });
                          })
                      }),
                  JsxRuntime.jsx(UiAction.make, {
                        onClick: (function (param) {
                            initializeRatings();
                          }),
                        children: t`Initialize Ratings`
                      }),
                  JsxRuntime.jsx(UiAction.make, {
                        onClick: (function (param) {
                            clearSession();
                          }),
                        children: t`Clear Session (Ratings, Match Counts, and Guest Players)`
                      })
                ],
                className: "grid grid-cols-1"
              });
          break;
      
    }
  } else {
    tmp = null;
  }
  return JsxRuntime.jsxs(Layout.Container.make, {
              children: [
                JsxRuntime.jsx(ReactHelmetAsync.Helmet, {
                      children: JsxRuntime.jsx("meta", {
                            content: "width=device-width",
                            name: "viewport"
                          })
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsxs("div", {
                                      children: [
                                        JsxRuntime.jsx(UiAction.make, {
                                              onClick: (function (param) {
                                                  setScreen(function (param) {
                                                        return "Matches";
                                                      });
                                                }),
                                              className: "rounded-md bg-indigo-600 px-3.5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600",
                                              children: t`Easy Mode`
                                            }),
                                        JsxRuntime.jsxs(React$1.Field, {
                                              className: "flex items-center ml-2",
                                              children: [
                                                JsxRuntime.jsxs(React$1.Switch, {
                                                      className: "group relative inline-flex h-6 w-11 flex-shrink-0 cursor-pointer rounded-full border-2 border-transparent bg-gray-200 transition-colors duration-200 ease-in-out focus:outline-none focus:ring-2 focus:ring-indigo-600 focus:ring-offset-2 data-[checked]:bg-indigo-600",
                                                      children: [
                                                        JsxRuntime.jsx("span", {
                                                              children: t`Tournament Mode`,
                                                              className: "sr-only"
                                                            }),
                                                        JsxRuntime.jsx("span", {
                                                              "aria-hidden": true,
                                                              className: "pointer-events-none inline-block h-5 w-5 transform rounded-full bg-white shadow ring-0 transition duration-200 ease-in-out group-data-[checked]:translate-x-5"
                                                            })
                                                      ],
                                                      checked: sessionMode,
                                                      onChange: (function (v) {
                                                          setSessionMode(function (param) {
                                                                return v;
                                                              });
                                                          if (v === true) {
                                                            return initializeSessionMode();
                                                          } else {
                                                            return uninitializeSessionMode();
                                                          }
                                                        })
                                                    }),
                                                JsxRuntime.jsx(React$1.Switch.Label, {
                                                      className: "ml-3 text-sm",
                                                      children: t`Tournament Mode`
                                                    })
                                              ]
                                            })
                                      ],
                                      className: "md:col-span-2 flex"
                                    }),
                                JsxRuntime.jsxs("div", {
                                      children: [
                                        JsxRuntime.jsx("h2", {
                                              children: t`Players`,
                                              className: "text-2xl font-semibold text-gray-900"
                                            }),
                                        JsxRuntime.jsxs("div", {
                                              children: [
                                                JsxRuntime.jsx(UiAction.make, {
                                                      onClick: (function (param) {
                                                          selectAllPlayers();
                                                        }),
                                                      children: t`Toggle All`
                                                    }),
                                                JsxRuntime.jsx(UiAction.make, {
                                                      onClick: (function (param) {
                                                          setSettingsPane(function (prev) {
                                                                if (Caml_obj.equal(prev, "TeamBuilder")) {
                                                                  return ;
                                                                } else {
                                                                  return "TeamBuilder";
                                                                }
                                                              });
                                                        }),
                                                      className: "ml-auto",
                                                      children: Caml_obj.equal(settingsPane, "TeamBuilder") ? JsxRuntime.jsx(Solid.UsersIcon, {
                                                              className: "h-8 w-8"
                                                            }) : JsxRuntime.jsx(Outline.UsersIcon, {
                                                              className: "h-8 w-8"
                                                            })
                                                    }),
                                                JsxRuntime.jsx(UiAction.make, {
                                                      onClick: (function (param) {
                                                          setSettingsPane(function (prev) {
                                                                if (Caml_obj.equal(prev, "AddPlayer")) {
                                                                  return ;
                                                                } else {
                                                                  return "AddPlayer";
                                                                }
                                                              });
                                                        }),
                                                      className: "ml-2",
                                                      children: Caml_obj.equal(settingsPane, "AddPlayer") ? JsxRuntime.jsx(Solid.UserPlusIcon, {
                                                              className: "h-8 w-8"
                                                            }) : JsxRuntime.jsx(Outline.UserPlusIcon, {
                                                              className: "h-8 w-8"
                                                            })
                                                    }),
                                                JsxRuntime.jsx(UiAction.make, {
                                                      onClick: (function (param) {
                                                          setSettingsPane(function (prev) {
                                                                if (Caml_obj.equal(prev, "Settings")) {
                                                                  return ;
                                                                } else {
                                                                  return "Settings";
                                                                }
                                                              });
                                                        }),
                                                      className: "ml-2",
                                                      children: Caml_obj.equal(settingsPane, "Settings") ? JsxRuntime.jsx(Solid.Cog6ToothIcon, {
                                                              className: "h-8 w-8"
                                                            }) : JsxRuntime.jsx(Outline.Cog6ToothIcon, {
                                                              className: "h-8 w-8"
                                                            })
                                                    })
                                              ],
                                              className: "flex text-right"
                                            }),
                                        tmp,
                                        JsxRuntime.jsx("div", {
                                              children: t`${breakPlayersCount.toString()} ${breakPlayersDesc} are not playing`
                                            }),
                                        JsxRuntime.jsx(SelectPlayersList.make, {
                                              players: allPlayers,
                                              selected: queue$1,
                                              playing: consumedPlayers,
                                              disabled: disabled,
                                              session: sessionState,
                                              onClick: toggleQueuePlayer,
                                              onRemove: (function (player) {
                                                  var match = player.data;
                                                  if (match !== undefined) {
                                                    return setDisabled(function (disabled) {
                                                                return addToQueue(disabled, player);
                                                              });
                                                  } else {
                                                    return setSessionPlayers(function (guests) {
                                                                return guests.filter(function (p) {
                                                                            return p.id !== player.id;
                                                                          });
                                                              });
                                                  }
                                                }),
                                              onEnable: (function (player) {
                                                  var match = player.data;
                                                  if (match !== undefined) {
                                                    return setDisabled(function (disabled) {
                                                                return removeFromQueue(disabled, player);
                                                              });
                                                  }
                                                  
                                                })
                                            })
                                      ],
                                      className: ""
                                    }),
                                JsxRuntime.jsxs("div", {
                                      children: [
                                        JsxRuntime.jsx("h2", {
                                              children: t`Matchmaking`,
                                              className: "text-2xl font-semibold text-gray-900"
                                            }),
                                        JsxRuntime.jsx("div", {
                                              className: "flex text-right"
                                            }),
                                        JsxRuntime.jsx(CompMatch.make, {
                                              players: queuedPlayers,
                                              teams: teams,
                                              consumedPlayers: new Set(),
                                              seenTeams: seenTeams,
                                              lastRoundSeenTeams: lastRoundSeenTeams,
                                              priorityPlayers: priorityPlayers,
                                              avoidAllPlayers: avoidAllPlayers,
                                              onSelectMatch: (function (match) {
                                                  queueMatch(match);
                                                })
                                            })
                                      ],
                                      className: ""
                                    })
                              ],
                              className: "grid grid-cols-1 items-start gap-4 md:grid-cols-2 md:gap-8"
                            }),
                        JsxRuntime.jsx("div", {
                              children: JsxRuntime.jsx(UiAction.make, {
                                    onClick: (function (param) {
                                        setManualTeamOpen(function (prev) {
                                              return !prev;
                                            });
                                      }),
                                    children: t`manual team`
                                  }),
                              className: "col-span-1"
                            }),
                        match$4[0] ? JsxRuntime.jsx(SelectMatch.make, {
                                players: queuedPlayers,
                                activity: activity,
                                onMatchQueued: (function (match) {
                                    queueMatch(match);
                                  }),
                                children: (function (match) {
                                    return Core__Option.getOr(Core__Option.map(activity, (function (activity) {
                                                      return JsxRuntime.jsx(React.Suspense, {
                                                                  children: Caml_option.some(JsxRuntime.jsx(SubmitMatch.make, {
                                                                            match: match,
                                                                            minRating: minRating,
                                                                            maxRating: maxRating,
                                                                            onComplete: (function (__x) {
                                                                                return handleMatchComplete(__x, -1);
                                                                              })
                                                                          })),
                                                                  fallback: Caml_option.some(JsxRuntime.jsx("div", {
                                                                            children: t`Loading`
                                                                          }))
                                                                });
                                                    })), null);
                                  })
                              }) : null,
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx("h2", {
                                      children: t`Submitted Matches`,
                                      className: "text-2xl font-semibold text-gray-900"
                                    }),
                                props.children
                              ]
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx("h2", {
                                      children: t`Match History`,
                                      className: "text-2xl font-semibold text-gray-900"
                                    }),
                                Core__Option.getOr(Core__Option.map(activity, (function (activity) {
                                            return matchHistory.map(function (param, i) {
                                                        console.log("Rendering history");
                                                        return JsxRuntime.jsx(SubmitMatch.make, {
                                                                    match: param[0],
                                                                    score: param[1],
                                                                    minRating: minRating,
                                                                    maxRating: maxRating,
                                                                    onDelete: (function () {
                                                                        setMatchHistory(function (mh) {
                                                                              var mh$1 = mh.filter(function (param, i$p) {
                                                                                    return i !== i$p;
                                                                                  });
                                                                              Rating.CompletedMatches.saveMatches(mh$1, eventId);
                                                                              return mh$1;
                                                                            });
                                                                      }),
                                                                    onComplete: (function (param) {
                                                                        var score = param[1];
                                                                        var match = param[0];
                                                                        return Core__Option.getOr(Core__Option.map(activity.slug, (function (slug) {
                                                                                          return Rating.CompletedMatch.submit([
                                                                                                      match,
                                                                                                      score
                                                                                                    ], slug, submitMatch);
                                                                                        })), Promise.resolve());
                                                                      })
                                                                  }, i.toString());
                                                      });
                                          })), null)
                              ]
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx("h2", {
                                      children: t`Queued Matches`,
                                      className: "text-2xl font-semibold text-gray-900"
                                    }),
                                JsxRuntime.jsxs("div", {
                                      children: [
                                        Core__Option.getOr(Core__Option.map(activity, (function (activity) {
                                                    return matches.map(function (match, i) {
                                                                return JsxRuntime.jsx(SubmitMatch.make, {
                                                                            match: match,
                                                                            minRating: minRating,
                                                                            maxRating: maxRating,
                                                                            onDelete: (function () {
                                                                                Core__Option.map(matches[i], (function (match) {
                                                                                        return [
                                                                                                    match[0],
                                                                                                    match[1]
                                                                                                  ].flatMap(function (x) {
                                                                                                      return x;
                                                                                                    }).map(function (p) {
                                                                                                    setQueue(function (queue) {
                                                                                                          return addToQueue(queue, p);
                                                                                                        });
                                                                                                  });
                                                                                      }));
                                                                                dequeueMatch(i);
                                                                              }),
                                                                            onComplete: (function (match) {
                                                                                return handleMatchComplete(match, i);
                                                                              })
                                                                          }, i.toString());
                                                              });
                                                  })), null),
                                        JsxRuntime.jsx("input", {
                                              readOnly: true,
                                              value: matches.map(function (param, i) {
                                                      var team1 = param[0].map(function (p) {
                                                              return p.name;
                                                            }).join(" " + t`and` + " ");
                                                      var team2 = param[1].map(function (p) {
                                                              return p.name;
                                                            }).join(" " + t`and` + " ");
                                                      return t`Court ${(i + 1 | 0).toString()}: ${team1} versus ${team2}`;
                                                    }).join(", ")
                                            })
                                      ],
                                      className: "grid grid-cols-1 gap-4"
                                    })
                              ],
                              className: "grid grid-cols-1 gap-4"
                            })
                      ],
                      className: "grid grid-cols-1 items-start gap-4 md:grid-cols-1 md:gap-8"
                    })
              ],
              className: "mt-4"
            });
}

var make = AiTetsu;

export {
  make ,
}
/*  Not a pure module */
