// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Util from "../shared/Util.re.mjs";
import * as React from "react";
import * as Caml_obj from "rescript/lib/es6/caml_obj.js";
import * as TimeWindow from "../molecules/TimeWindow.re.mjs";
import * as ReactIntl from "react-intl";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Core__Array from "@rescript/core/src/Core__Array.re.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.re.mjs";
import * as LangProvider from "../shared/LangProvider.re.mjs";
import * as LucideReact from "lucide-react";
import * as RelayRuntime from "relay-runtime";
import * as Belt_SetString from "rescript/lib/es6/belt_SetString.js";
import * as JsxRuntime from "react/jsx-runtime";
import * as AvatarWithProgress from "../molecules/AvatarWithProgress.re.mjs";
import * as RescriptRelay_Query from "rescript-relay/src/RescriptRelay_Query.re.mjs";
import * as PlayerInviteSwipeDeck from "./PlayerInviteSwipeDeck.re.mjs";
import * as RescriptRelay_Mutation from "rescript-relay/src/RescriptRelay_Mutation.re.mjs";
import * as EventInvitesMutation_graphql from "../../__generated__/EventInvitesMutation_graphql.re.mjs";
import * as EventInvitesCandidatesQuery_graphql from "../../__generated__/EventInvitesCandidatesQuery_graphql.re.mjs";

import { t } from '@lingui/macro'
;

var convertVariables = EventInvitesMutation_graphql.Internal.convertVariables;

var convertResponse = EventInvitesMutation_graphql.Internal.convertResponse;

var convertWrapRawResponse = EventInvitesMutation_graphql.Internal.convertWrapRawResponse;

var commitMutation = RescriptRelay_Mutation.commitMutation(convertVariables, EventInvitesMutation_graphql.node, convertResponse, convertWrapRawResponse);

var use = RescriptRelay_Mutation.useMutation(convertVariables, EventInvitesMutation_graphql.node, convertResponse, convertWrapRawResponse);

var InviteMutation_gender_decode = EventInvitesMutation_graphql.Utils.gender_decode;

var InviteMutation_gender_fromString = EventInvitesMutation_graphql.Utils.gender_fromString;

var InviteMutation = {
  gender_decode: InviteMutation_gender_decode,
  gender_fromString: InviteMutation_gender_fromString,
  Operation: undefined,
  Types: undefined,
  convertVariables: convertVariables,
  convertResponse: convertResponse,
  convertWrapRawResponse: convertWrapRawResponse,
  commitMutation: commitMutation,
  use: use
};

var convertVariables$1 = EventInvitesCandidatesQuery_graphql.Internal.convertVariables;

var convertResponse$1 = EventInvitesCandidatesQuery_graphql.Internal.convertResponse;

var convertWrapRawResponse$1 = EventInvitesCandidatesQuery_graphql.Internal.convertWrapRawResponse;

var use$1 = RescriptRelay_Query.useQuery(convertVariables$1, EventInvitesCandidatesQuery_graphql.node, convertResponse$1);

var useLoader = RescriptRelay_Query.useLoader(convertVariables$1, EventInvitesCandidatesQuery_graphql.node, (function (prim) {
        return prim;
      }));

var usePreloaded = RescriptRelay_Query.usePreloaded(EventInvitesCandidatesQuery_graphql.node, convertResponse$1, (function (prim) {
        return prim;
      }));

var $$fetch = RescriptRelay_Query.$$fetch(EventInvitesCandidatesQuery_graphql.node, convertResponse$1, convertVariables$1);

var fetchPromised = RescriptRelay_Query.fetchPromised(EventInvitesCandidatesQuery_graphql.node, convertResponse$1, convertVariables$1);

var retain = RescriptRelay_Query.retain(EventInvitesCandidatesQuery_graphql.node, convertVariables$1);

var CandidatesQuery = {
  Operation: undefined,
  Types: undefined,
  convertVariables: convertVariables$1,
  convertResponse: convertResponse$1,
  convertWrapRawResponse: convertWrapRawResponse$1,
  use: use$1,
  useLoader: useLoader,
  usePreloaded: usePreloaded,
  $$fetch: $$fetch,
  fetchPromised: fetchPromised,
  retain: retain
};

function EventInvites$CandidatesLoader(props) {
  var onLoaded = props.onLoaded;
  var evEnd = props.evEnd;
  var evStart = props.evStart;
  var data = use$1({
        activityId: props.activityId,
        activitySlug: props.activitySlug,
        clubId: props.clubId,
        localDate: props.localDate
      }, "store-or-network", undefined, undefined);
  React.useEffect((function () {
          var candidates = Core__Array.filterMap(data.availabilityUsersForDay.filter(function (day) {
                    return day.intervals.some(function (iv) {
                                if (iv.startHour <= evStart) {
                                  return iv.endHour >= evEnd;
                                } else {
                                  return false;
                                }
                              });
                  }), (function (day) {
                  return Core__Option.map(day.user, (function (u) {
                                return {
                                        id: u.id,
                                        name: Core__Option.getOr(u.lineUsername, "?"),
                                        picture: u.picture,
                                        user: u.fragmentRefs
                                      };
                              }));
                }));
          onLoaded(candidates);
        }), [data]);
  return null;
}

var CandidatesLoader = {
  make: EventInvites$CandidatesLoader
};

function EventInvites(props) {
  var participantUserIds = props.participantUserIds;
  var timezone = props.timezone;
  var endDate = props.endDate;
  var startDate = props.startDate;
  var activitySlug = props.activitySlug;
  var activityId = props.activityId;
  var eventId = props.eventId;
  var intl = ReactIntl.useIntl();
  var nav = LangProvider.Router.useNavigate();
  var match = use();
  var commitInvite = match[0];
  var match$1 = React.useState(function () {
        return [];
      });
  var setCandidates = match$1[1];
  var match$2 = React.useState(function () {
        
      });
  var setSentIds = match$2[1];
  var sentIds = match$2[0];
  var match$3 = React.useState(function () {
        
      });
  var setActiveMenuId = match$3[1];
  var activeMenuId = match$3[0];
  var match$4 = React.useState(function () {
        return false;
      });
  var setSwipeOpen = match$4[1];
  var match$5 = React.useState(function () {
        return false;
      });
  var setMounted = match$5[1];
  React.useEffect((function () {
          setMounted(function (param) {
                return true;
              });
        }), []);
  var $$window;
  if (startDate !== undefined && endDate !== undefined) {
    var startD = Util.Datetime.toDate(Caml_option.valFromOption(startDate));
    var endD = Util.Datetime.toDate(Caml_option.valFromOption(endDate));
    var evStart = TimeWindow.hourInTimeZone(startD, timezone);
    var evEndRaw = TimeWindow.hourInTimeZone(endD, timezone);
    var evEnd = evEndRaw <= evStart ? 24 : evEndRaw;
    var opts = {
      timeZone: timezone,
      year: "numeric",
      month: "2-digit",
      day: "2-digit"
    };
    var parts = intl.formatDateToParts(startD, opts);
    var getVal = function (t) {
      return Core__Option.getOr(Core__Option.map(parts.find(function (p) {
                          return p.type === t;
                        }), (function (p) {
                        return p.value;
                      })), "0");
    };
    var localDate = getVal("year") + "-" + getVal("month") + "-" + getVal("day");
    var fmtTime = function (d) {
      return intl.formatTime(d, {
                  timeZone: timezone
                });
    };
    $$window = [
      localDate,
      evStart,
      evEnd,
      fmtTime(startD) + "–" + fmtTime(endD)
    ];
  } else {
    $$window = undefined;
  }
  var visibleCandidates = match$1[0].filter(function (c) {
        if (participantUserIds.includes(c.id)) {
          return false;
        } else {
          return !Belt_SetString.has(sentIds, c.id);
        }
      });
  var handleInvite = function (userId) {
    var alreadyInvited = participantUserIds.includes(userId) || Belt_SetString.has(sentIds, userId);
    if (alreadyInvited) {
      return ;
    }
    setSentIds(function (s) {
          return Belt_SetString.add(s, userId);
        });
    var connectionId = RelayRuntime.ConnectionHandler.getConnectionID(eventId, "PkRSVPSection_event_rsvps", undefined);
    commitInvite({
          connections: [connectionId],
          eventId: eventId,
          userId: userId
        }, undefined, undefined, undefined, (function (response, param) {
            var errors = response.inviteToEvent.errors;
            if (errors !== undefined && errors.length > 0) {
              return setSentIds(function (s) {
                          return Belt_SetString.remove(s, userId);
                        });
            }
            
          }), (function (param) {
            setSentIds(function (s) {
                  return Belt_SetString.remove(s, userId);
                });
          }), undefined);
  };
  var inviteableCount = visibleCandidates.length;
  var totalCount = props.invitedCount + inviteableCount | 0;
  return JsxRuntime.jsxs(JsxRuntime.Fragment, {
              children: [
                props.canInvite && match$5[0] && $$window !== undefined && activityId !== undefined ? JsxRuntime.jsx(React.Suspense, {
                        children: Caml_option.some(JsxRuntime.jsx(EventInvites$CandidatesLoader, {
                                  localDate: $$window[0],
                                  activityId: activityId,
                                  clubId: props.clubId,
                                  activitySlug: Core__Option.getOr(activitySlug, "pickleball"),
                                  evStart: $$window[1],
                                  evEnd: $$window[2],
                                  onLoaded: (function (c) {
                                      setCandidates(function (param) {
                                            return c;
                                          });
                                    })
                                })),
                        fallback: Caml_option.some(null)
                      }) : null,
                totalCount === 0 ? null : JsxRuntime.jsxs("section", {
                        children: [
                          JsxRuntime.jsxs("div", {
                                children: [
                                  JsxRuntime.jsx("div", {
                                        className: "h-px flex-1 bg-violet-200 dark:bg-violet-800/50"
                                      }),
                                  JsxRuntime.jsxs("span", {
                                        children: [
                                          JsxRuntime.jsx(LucideReact.Mail, {
                                                size: 10,
                                                "aria-hidden": "true"
                                              }),
                                          t`Invites · ${totalCount.toString()}`
                                        ],
                                        className: "font-mono text-[11px] tracking-wider text-violet-600 dark:text-violet-400 uppercase inline-flex items-center gap-1",
                                        id: "invites-heading"
                                      }),
                                  JsxRuntime.jsx("div", {
                                        className: "h-px flex-1 bg-violet-200 dark:bg-violet-800/50"
                                      }),
                                  inviteableCount > 0 ? JsxRuntime.jsxs("button", {
                                          children: [
                                            JsxRuntime.jsx(LucideReact.Layers, {
                                                  size: 10,
                                                  strokeWidth: 2.5,
                                                  "aria-hidden": "true"
                                                }),
                                            t`Swipe invites`
                                          ],
                                          "aria-label": t`Review ${inviteableCount.toString()} potential players with swipe cards`,
                                          className: "absolute right-0 top-1/2 inline-flex -translate-y-1/2 items-center gap-1 rounded-md bg-violet-600 px-2 py-1 text-[9px] font-semibold text-white transition-colors hover:bg-violet-700 focus:outline-none focus-visible:ring-2 focus-visible:ring-violet-500 focus-visible:ring-offset-2 dark:bg-violet-500 dark:hover:bg-violet-400 dark:hover:text-violet-950",
                                          type: "button",
                                          onClick: (function (param) {
                                              setSwipeOpen(function (param) {
                                                    return true;
                                                  });
                                            })
                                        }) : null
                                ],
                                className: "relative flex items-center gap-2 mb-2"
                              }),
                          JsxRuntime.jsxs("ul", {
                                children: [
                                  props.invitedChips,
                                  visibleCandidates.map(function (c) {
                                        var menuOpen = Caml_obj.equal(activeMenuId, c.id);
                                        return JsxRuntime.jsxs("li", {
                                                    children: [
                                                      JsxRuntime.jsxs("button", {
                                                            children: [
                                                              JsxRuntime.jsx(AvatarWithProgress.make, {
                                                                    src: Core__Option.getOr(c.picture, ""),
                                                                    alt: c.name,
                                                                    progress: 0,
                                                                    size: 22,
                                                                    strokeWidth: 1.5
                                                                  }),
                                                              JsxRuntime.jsx("span", {
                                                                    children: c.name,
                                                                    className: "text-[11px] leading-none text-violet-900 dark:text-violet-200"
                                                                  }),
                                                              JsxRuntime.jsx("span", {
                                                                    children: t`invite`,
                                                                    className: "font-mono text-[9px] leading-none text-violet-500 dark:text-violet-400"
                                                                  })
                                                            ],
                                                            "aria-label": t`Open invite actions for ${c.name}`,
                                                            "aria-expanded": menuOpen,
                                                            "aria-haspopup": "menu",
                                                            className: "relative inline-flex items-center gap-1.5 rounded-full border border-violet-200 dark:border-violet-800/60 bg-violet-50 dark:bg-violet-950/20 py-0.5 pl-0.5 pr-2 opacity-50 transition-[opacity,background-color] hover:bg-violet-100 dark:hover:bg-violet-900/30 hover:opacity-100 focus:outline-none focus-visible:opacity-100 focus-visible:ring-2 focus-visible:ring-violet-500 focus-visible:ring-offset-2",
                                                            type: "button",
                                                            onClick: (function (param) {
                                                                setActiveMenuId(function (cur) {
                                                                      if (Caml_obj.equal(cur, c.id)) {
                                                                        return ;
                                                                      } else {
                                                                        return c.id;
                                                                      }
                                                                    });
                                                              })
                                                          }),
                                                      menuOpen ? JsxRuntime.jsxs(JsxRuntime.Fragment, {
                                                              children: [
                                                                JsxRuntime.jsx("div", {
                                                                      className: "fixed inset-0 z-40",
                                                                      onClick: (function (param) {
                                                                          setActiveMenuId(function (param) {
                                                                                
                                                                              });
                                                                        })
                                                                    }),
                                                                JsxRuntime.jsxs("div", {
                                                                      children: [
                                                                        JsxRuntime.jsxs("button", {
                                                                              children: [
                                                                                JsxRuntime.jsx(LucideReact.User, {
                                                                                      className: "w-3 h-3"
                                                                                    }),
                                                                                t`View Profile`
                                                                              ],
                                                                              className: "flex w-full items-center gap-2 px-3 py-2 text-left text-xs text-gray-700 dark:text-gray-300 transition-colors hover:bg-gray-50 dark:hover:bg-[#353640] focus:bg-gray-50 dark:focus:bg-[#353640] focus:outline-none",
                                                                              role: "menuitem",
                                                                              type: "button",
                                                                              onClick: (function (param) {
                                                                                  setActiveMenuId(function (param) {
                                                                                        
                                                                                      });
                                                                                  nav("/league/" + Core__Option.getOr(activitySlug, "pickleball") + "/p/" + c.id, undefined);
                                                                                })
                                                                            }),
                                                                        JsxRuntime.jsxs("button", {
                                                                              children: [
                                                                                JsxRuntime.jsx(LucideReact.Send, {
                                                                                      className: "w-3 h-3"
                                                                                    }),
                                                                                t`Send invite`
                                                                              ],
                                                                              className: "flex w-full items-center gap-2 px-3 py-2 text-left text-xs font-medium text-violet-700 dark:text-violet-300 transition-colors hover:bg-violet-50 dark:hover:bg-violet-950/30 focus:bg-violet-50 dark:focus:bg-violet-950/30 focus:outline-none",
                                                                              role: "menuitem",
                                                                              type: "button",
                                                                              onClick: (function (param) {
                                                                                  setActiveMenuId(function (param) {
                                                                                        
                                                                                      });
                                                                                  handleInvite(c.id);
                                                                                })
                                                                            })
                                                                      ],
                                                                      className: "absolute left-0 top-full z-50 mt-1 w-36 overflow-hidden rounded-lg border border-gray-200 dark:border-[#3a3b40] bg-white dark:bg-[#2a2b30] py-1 shadow-lg",
                                                                      role: "menu"
                                                                    })
                                                              ]
                                                            }) : null
                                                    ],
                                                    className: "relative",
                                                    onKeyDown: (function (e) {
                                                        if (e.key === "Escape") {
                                                          return setActiveMenuId(function (param) {
                                                                      
                                                                    });
                                                        }
                                                        
                                                      })
                                                  }, c.id);
                                      })
                                ],
                                "aria-label": t`Invited and potential players`,
                                className: "flex flex-wrap gap-1.5 list-none p-0 m-0"
                              }),
                          match$4[0] && $$window !== undefined ? JsxRuntime.jsx(PlayerInviteSwipeDeck.make, {
                                  players: visibleCandidates.map(function (c) {
                                        return {
                                                id: c.id,
                                                name: c.name,
                                                source: {
                                                  TAG: "FromFragment",
                                                  _0: c.user
                                                }
                                              };
                                      }),
                                  eventTitle: props.eventTitle,
                                  eventVenue: props.venueName,
                                  eventTimeLabel: $$window[3],
                                  mode: "Invite",
                                  onAccept: handleInvite,
                                  onClose: (function () {
                                      setSwipeOpen(function (param) {
                                            return false;
                                          });
                                    })
                                }) : null
                        ],
                        "aria-labelledby": "invites-heading",
                        className: "mt-2.5"
                      })
              ]
            });
}

var make = EventInvites;

export {
  InviteMutation ,
  CandidatesQuery ,
  CandidatesLoader ,
  make ,
}
/*  Not a pure module */
