// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Option from "@rescript/core/src/Core__Option.re.mjs";
import * as AvatarRsvpUser from "./AvatarRsvpUser.re.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import * as RescriptRelay_Fragment from "rescript-relay/src/RescriptRelay_Fragment.re.mjs";
import * as EventRsvpUser_user_graphql from "../../__generated__/EventRsvpUser_user_graphql.re.mjs";

var convertFragment = EventRsvpUser_user_graphql.Internal.convertFragment;

function use(fRef) {
  return RescriptRelay_Fragment.useFragment(EventRsvpUser_user_graphql.node, convertFragment, fRef);
}

function fromRegisteredUser(user) {
  return {
          name: Core__Option.getOr(user.lineUsername, "[Line username missing]"),
          picture: user.picture
        };
}

function EventRsvpUser(props) {
  var __highlight = props.highlight;
  var highlight = __highlight !== undefined ? __highlight : false;
  var user = use(props.user);
  var userData = fromRegisteredUser(user);
  return JsxRuntime.jsx(AvatarRsvpUser.make, {
              user: userData,
              highlight: highlight,
              link: props.link,
              secondaryText: props.secondaryText,
              sigmaPercent: props.sigmaPercent,
              ratingPercent: props.ratingPercent
            });
}

var make = EventRsvpUser;

export {
  make ,
}
/* AvatarRsvpUser Not a pure module */
