// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Layout from "../shared/Layout.re.mjs";
import * as Rating from "../../lib/Rating.re.mjs";
import * as Router from "../shared/Router.re.mjs";
import * as Caml_obj from "rescript/lib/es6/caml_obj.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Core__Array from "@rescript/core/src/Core__Array.re.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.re.mjs";
import * as LangProvider from "../shared/LangProvider.re.mjs";
import * as LucideReact from "lucide-react";
import * as Core from "@linaria/core";
import * as ReactRouterDom from "react-router-dom";
import * as ReactExperimental from "rescript-relay/src/ReactExperimental.re.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import * as RescriptRelay_Fragment from "rescript-relay/src/RescriptRelay_Fragment.re.mjs";
import * as RatingList_rating_graphql from "../../__generated__/RatingList_rating_graphql.re.mjs";
import * as RatingListFragment_graphql from "../../__generated__/RatingListFragment_graphql.re.mjs";
import * as RatingListRefetchQuery_graphql from "../../__generated__/RatingListRefetchQuery_graphql.re.mjs";

import { css, cx } from '@linaria/core'
;

import { t, plural } from '@lingui/macro'
;

var getConnectionNodes = RatingListFragment_graphql.Utils.getConnectionNodes;

var convertFragment = RatingListFragment_graphql.Internal.convertFragment;

function use(fRef) {
  return RescriptRelay_Fragment.useFragment(RatingListFragment_graphql.node, convertFragment, fRef);
}

function useOpt(fRef) {
  return RescriptRelay_Fragment.useFragmentOpt(fRef !== undefined ? Caml_option.some(Caml_option.valFromOption(fRef)) : undefined, RatingListFragment_graphql.node, convertFragment);
}

var makeRefetchVariables = RatingListRefetchQuery_graphql.Types.makeRefetchVariables;

var convertRefetchVariables = RatingListRefetchQuery_graphql.Internal.convertVariables;

function useRefetchable(fRef) {
  return RescriptRelay_Fragment.useRefetchableFragment(RatingListFragment_graphql.node, convertFragment, convertRefetchVariables, fRef);
}

function usePagination(fRef) {
  return RescriptRelay_Fragment.usePaginationFragment(RatingListFragment_graphql.node, fRef, convertFragment, convertRefetchVariables);
}

function useBlockingPagination(fRef) {
  return RescriptRelay_Fragment.useBlockingPaginationFragment(RatingListFragment_graphql.node, fRef, convertFragment, convertRefetchVariables);
}

var Fragment_gender_decode = RatingListFragment_graphql.Utils.gender_decode;

var Fragment_gender_fromString = RatingListFragment_graphql.Utils.gender_fromString;

var Fragment = {
  getConnectionNodes: getConnectionNodes,
  gender_decode: Fragment_gender_decode,
  gender_fromString: Fragment_gender_fromString,
  Types: undefined,
  Operation: undefined,
  convertFragment: convertFragment,
  use: use,
  useOpt: useOpt,
  makeRefetchVariables: makeRefetchVariables,
  convertRefetchVariables: convertRefetchVariables,
  useRefetchable: useRefetchable,
  usePagination: usePagination,
  useBlockingPagination: useBlockingPagination
};

var convertFragment$1 = RatingList_rating_graphql.Internal.convertFragment;

function use$1(fRef) {
  return RescriptRelay_Fragment.useFragment(RatingList_rating_graphql.node, convertFragment$1, fRef);
}

function useOpt$1(fRef) {
  return RescriptRelay_Fragment.useFragmentOpt(fRef !== undefined ? Caml_option.some(Caml_option.valFromOption(fRef)) : undefined, RatingList_rating_graphql.node, convertFragment$1);
}

var ItemFragment_gender_decode = RatingList_rating_graphql.Utils.gender_decode;

var ItemFragment_gender_fromString = RatingList_rating_graphql.Utils.gender_fromString;

var ItemFragment = {
  gender_decode: ItemFragment_gender_decode,
  gender_fromString: ItemFragment_gender_fromString,
  Types: undefined,
  Operation: undefined,
  convertFragment: convertFragment$1,
  use: use$1,
  useOpt: useOpt$1
};

var $$IntersectionObserver = {};

function initialsOf(name) {
  var parts = name.trim().split(" ").filter(function (p) {
        return p !== "";
      });
  var len = parts.length;
  if (len !== 1) {
    if (len !== 0) {
      return parts.map(function (p) {
                        return p.slice(0, 1);
                      }).slice(0, 2).join("").toUpperCase();
    } else {
      return "?";
    }
  }
  var single = parts[0];
  return single.slice(0, 2).toUpperCase();
}

function RatingList$RatingItem(props) {
  var minRating = props.minRating;
  var maxRating = props.maxRating;
  var rank = props.rank;
  var match = use$1(props.rating);
  var ordinal = match.ordinal;
  var progress = ordinal !== undefined ? (
      maxRating === minRating ? 100 : (ordinal - minRating) / (maxRating - minRating) * 100
    ) : 0;
  var isLeader = progress >= 100;
  var qualifies = props.draftEnabled && Core__Option.getOr(Core__Option.map(props.genderRank, (function (r) {
              return r <= 8;
            })), false);
  var progressPct = progress.toFixed(2) + "%";
  var dupr = Core__Option.map(match.mu, (function (mu) {
          return Rating.guessDupr(mu).toFixed(2);
        }));
  return Core__Option.getOr(Core__Option.map(match.user, (function (user) {
                    var name = Core__Option.getOr(user.lineUsername, "?");
                    var daysAtOne = Core__Option.map(user.leagueUserStats, (function (s) {
                            return s.daysNumberOne;
                          }));
                    return JsxRuntime.jsxs("li", {
                                children: [
                                  JsxRuntime.jsx("div", {
                                        className: Core.cx("absolute inset-y-0 left-0 pointer-events-none transition-[width] duration-700 ease-out", isLeader ? "bg-yellow-400/30 dark:bg-yellow-400/25" : "bg-[#bdf25d]/30 dark:bg-[#bdf25d]/20"),
                                        style: {
                                          width: progressPct,
                                          clipPath: "polygon(0 0, 100% 0, calc(100% - 18px) 100%, 0 100%)"
                                        }
                                      }),
                                  JsxRuntime.jsx("div", {
                                        className: Core.cx("absolute inset-y-0 -ml-3 w-1.5 pointer-events-none transform -skew-x-12 transition-[left] duration-700 ease-out", isLeader ? "bg-yellow-400 shadow-[0_0_10px_rgba(250,204,21,0.6)]" : "bg-[#bdf25d] shadow-[0_0_10px_rgba(189,242,93,0.5)]"),
                                        style: {
                                          left: progressPct
                                        }
                                      }),
                                  JsxRuntime.jsx("div", {
                                        children: JsxRuntime.jsx("span", {
                                              children: rank.toString(),
                                              className: Core.cx("font-black italic text-2xl md:text-3xl leading-none tabular-nums transition-colors", isLeader ? "text-yellow-500 dark:text-yellow-400" : "text-gray-400 dark:text-gray-500 group-hover:text-gray-900 dark:group-hover:text-white")
                                            }),
                                        className: "relative w-10 md:w-14 flex-shrink-0 text-center"
                                      }),
                                  JsxRuntime.jsxs("div", {
                                        children: [
                                          JsxRuntime.jsxs("div", {
                                                children: [
                                                  Core__Option.getOr(Core__Option.map(user.picture, (function (picture) {
                                                              return JsxRuntime.jsx("img", {
                                                                          className: "w-full h-full rounded-full object-cover",
                                                                          alt: "",
                                                                          src: picture
                                                                        });
                                                            })), initialsOf(name)),
                                                  Caml_obj.equal(user.gender, "female") ? JsxRuntime.jsx("span", {
                                                          className: "absolute -bottom-0.5 -right-0.5 w-3 h-3 rounded-full border-2 border-white dark:border-[#1e1f23] bg-pink-500"
                                                        }) : JsxRuntime.jsx("span", {
                                                          className: "absolute -bottom-0.5 -right-0.5 w-3 h-3 rounded-full border-2 border-white dark:border-[#1e1f23] bg-blue-500"
                                                        }),
                                                  isLeader ? JsxRuntime.jsx(LucideReact.Crown, {
                                                          size: 20,
                                                          fill: "currentColor",
                                                          className: "absolute -top-4 md:-top-5 text-yellow-400 drop-shadow-[0_0_8px_rgba(250,204,21,0.8)]"
                                                        }) : null
                                                ],
                                                className: Core.cx("relative w-10 h-10 md:w-11 md:h-11 rounded-full bg-gray-100 dark:bg-[#2a2b30] flex items-center justify-center font-black text-sm text-gray-800 dark:text-white flex-shrink-0 border-2", isLeader ? "border-yellow-400" : "border-transparent")
                                              }),
                                          JsxRuntime.jsxs("div", {
                                                children: [
                                                  JsxRuntime.jsxs("div", {
                                                        children: [
                                                          JsxRuntime.jsx("span", {
                                                                children: name,
                                                                className: "truncate"
                                                              }),
                                                          qualifies ? JsxRuntime.jsxs("span", {
                                                                  children: [
                                                                    JsxRuntime.jsx(LucideReact.Trophy, {
                                                                          size: 10,
                                                                          strokeWidth: 2.5
                                                                        }),
                                                                    t`Draft`
                                                                  ],
                                                                  className: "hidden md:inline-flex items-center gap-1 flex-shrink-0 px-1.5 py-0.5 rounded bg-amber-400/20 border border-amber-400/50 text-amber-700 dark:text-amber-300 font-mono text-[10px] font-black tracking-wider normal-case"
                                                                }) : null
                                                        ],
                                                        className: "font-bold text-sm md:text-lg uppercase tracking-wide text-gray-900 dark:text-white truncate flex items-center gap-2"
                                                      }),
                                                  JsxRuntime.jsxs("div", {
                                                        children: [
                                                          Core__Option.getOr(Core__Option.map(dupr, (function (dupr) {
                                                                      return JsxRuntime.jsx("div", {
                                                                                  children: "DUPR " + dupr,
                                                                                  className: "sm:hidden font-mono text-[10px] text-gray-500 dark:text-gray-400 font-bold"
                                                                                });
                                                                    })), null),
                                                          qualifies ? JsxRuntime.jsxs("span", {
                                                                  children: [
                                                                    JsxRuntime.jsx(LucideReact.Trophy, {
                                                                          size: 10,
                                                                          strokeWidth: 2.5
                                                                        }),
                                                                    t`Draft`
                                                                  ],
                                                                  className: "md:hidden inline-flex items-center gap-1 flex-shrink-0 font-mono text-[10px] font-black text-amber-600 dark:text-amber-400 uppercase tracking-wider"
                                                                }) : null
                                                        ],
                                                        className: "flex items-center gap-2 mt-0.5"
                                                      })
                                                ],
                                                className: "min-w-0"
                                              })
                                        ],
                                        className: "relative flex-1 ml-2 flex items-center gap-3 md:gap-4 min-w-0"
                                      }),
                                  JsxRuntime.jsx("div", {
                                        children: JsxRuntime.jsx("div", {
                                              children: Core__Option.getOr(Core__Option.map(ordinal, (function (ordinal) {
                                                          return ordinal.toFixed(2);
                                                        })), "--"),
                                              className: Core.cx("font-mono text-xl md:text-3xl font-black tabular-nums transition-colors", isLeader ? "text-yellow-500 dark:text-yellow-400" : "text-gray-900 dark:text-white")
                                            }),
                                        className: "relative w-24 md:w-32 text-right"
                                      }),
                                  JsxRuntime.jsx("div", {
                                        children: JsxRuntime.jsx("div", {
                                              children: Core__Option.getOr(Core__Option.map(dupr, (function (prim) {
                                                          return prim;
                                                        })), "--"),
                                              className: "font-mono text-sm font-bold text-gray-500 dark:text-gray-400"
                                            }),
                                        className: "relative w-20 text-right hidden sm:block"
                                      }),
                                  JsxRuntime.jsx("div", {
                                        children: Core__Option.getOr(Core__Option.map(Core__Option.flatMap(daysAtOne, (function (d) {
                                                        if (d > 0.0) {
                                                          return d;
                                                        }
                                                        
                                                      })), (function (d) {
                                                    return JsxRuntime.jsxs("div", {
                                                                children: [
                                                                  JsxRuntime.jsx(LucideReact.Crown, {
                                                                        size: 13,
                                                                        strokeWidth: 2.5,
                                                                        fill: "currentColor"
                                                                      }),
                                                                  JsxRuntime.jsx("span", {
                                                                        children: d.toFixed(1),
                                                                        className: "font-mono text-xs font-bold"
                                                                      })
                                                                ],
                                                                className: "flex items-center gap-1 text-amber-500 dark:text-amber-400"
                                                              });
                                                  })), JsxRuntime.jsx("span", {
                                                  children: "—",
                                                  className: "font-mono text-xs text-gray-300 dark:text-gray-600"
                                                })),
                                        className: "relative w-16 hidden md:flex justify-end items-center"
                                      }),
                                  JsxRuntime.jsx(LangProvider.Router.Link.make, {
                                        to: "./p/" + user.id,
                                        children: JsxRuntime.jsx("span", {
                                              children: name,
                                              className: "sr-only"
                                            }),
                                        className: "absolute inset-0 z-10"
                                      })
                                ],
                                className: Core.cx("group relative flex items-center overflow-hidden shadow-sm hover:shadow-[0_0_15px_rgba(189,242,93,0.2)] transition-all py-3.5 md:py-5 px-3 md:px-4 border-b", qualifies ? "bg-amber-50/60 dark:bg-amber-950/20 border-amber-200/70 dark:border-amber-500/20 border-l-2 border-l-amber-400" : "bg-white dark:bg-[#1e1f23] border-gray-200 dark:border-[#2a2b30]")
                              });
                  })), null);
}

var RatingItem = {
  make: RatingList$RatingItem
};

function RatingList$CurrentUserStanding(props) {
  var name = props.name;
  var dupr = props.dupr;
  var progressPct = props.progress.toFixed(2) + "%";
  return JsxRuntime.jsxs("aside", {
              children: [
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("span", {
                              children: t`Your standing`,
                              className: "font-mono text-[9px] font-black uppercase tracking-[0.18em] text-[#64851d] dark:text-[#bdf25d]"
                            }),
                        JsxRuntime.jsx("span", {
                              className: "h-px flex-1 bg-[#bdf25d]/35 dark:bg-[#bdf25d]/20"
                            })
                      ],
                      className: "mb-1.5 flex items-center gap-2 px-1"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("div", {
                              className: "pointer-events-none absolute inset-y-0 left-0 bg-[#bdf25d]/35 dark:bg-[#bdf25d]/20 transition-[width] duration-700 ease-out",
                              style: {
                                width: progressPct,
                                clipPath: "polygon(0 0, 100% 0, calc(100% - 18px) 100%, 0 100%)"
                              }
                            }),
                        JsxRuntime.jsx("div", {
                              className: "pointer-events-none absolute inset-y-0 -ml-3 w-1.5 -skew-x-12 bg-[#bdf25d] shadow-[0_0_10px_rgba(189,242,93,0.5)] transition-[left] duration-700 ease-out",
                              style: {
                                left: progressPct
                              }
                            }),
                        JsxRuntime.jsx("div", {
                              children: JsxRuntime.jsx("span", {
                                    children: props.rank.toString(),
                                    className: "text-2xl font-black italic leading-none tabular-nums text-[#64851d] md:text-3xl dark:text-[#bdf25d]"
                                  }),
                              className: "relative w-10 flex-shrink-0 text-center md:w-14"
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx("div", {
                                      children: Core__Option.getOr(Core__Option.map(props.picture, (function (picture) {
                                                  return JsxRuntime.jsx("img", {
                                                              className: "w-full h-full rounded-full object-cover",
                                                              alt: "",
                                                              src: picture
                                                            });
                                                })), initialsOf(name)),
                                      className: "flex h-10 w-10 flex-shrink-0 items-center justify-center overflow-hidden rounded-full border-2 border-[#bdf25d] bg-[#bdf25d]/20 text-sm font-black text-gray-900 md:h-11 md:w-11 dark:text-white"
                                    }),
                                JsxRuntime.jsxs("div", {
                                      children: [
                                        JsxRuntime.jsxs("div", {
                                              children: [
                                                JsxRuntime.jsx("span", {
                                                      children: name,
                                                      className: "truncate"
                                                    }),
                                                JsxRuntime.jsx("span", {
                                                      children: t`You`,
                                                      className: "rounded bg-[#bdf25d]/25 px-1.5 py-0.5 font-mono text-[9px] font-black normal-case tracking-wider text-[#526f16] dark:text-[#bdf25d]"
                                                    })
                                              ],
                                              className: "flex items-center gap-2 truncate text-sm font-bold uppercase tracking-wide text-gray-900 md:text-lg dark:text-white"
                                            }),
                                        Core__Option.getOr(Core__Option.map(dupr, (function (dupr) {
                                                    return JsxRuntime.jsx("div", {
                                                                children: "DUPR " + dupr,
                                                                className: "mt-0.5 font-mono text-[10px] font-bold text-gray-500 sm:hidden dark:text-gray-400"
                                                              });
                                                  })), null)
                                      ],
                                      className: "min-w-0"
                                    })
                              ],
                              className: "relative ml-2 flex min-w-0 flex-1 items-center gap-3 md:gap-4"
                            }),
                        JsxRuntime.jsx("div", {
                              children: JsxRuntime.jsx("div", {
                                    children: props.ordinal.toFixed(2),
                                    className: "font-mono text-xl font-black tabular-nums text-gray-900 md:text-3xl dark:text-white"
                                  }),
                              className: "relative w-24 text-right md:w-32"
                            }),
                        JsxRuntime.jsx("div", {
                              children: JsxRuntime.jsx("div", {
                                    children: Core__Option.getOr(Core__Option.map(dupr, (function (prim) {
                                                return prim;
                                              })), "--"),
                                    className: "font-mono text-sm font-bold text-gray-500 dark:text-gray-400"
                                  }),
                              className: "relative w-20 text-right hidden sm:block"
                            }),
                        JsxRuntime.jsx("div", {
                              children: Core__Option.getOr(Core__Option.map(Core__Option.flatMap(props.days, (function (d) {
                                              if (d > 0.0) {
                                                return d;
                                              }
                                              
                                            })), (function (d) {
                                          return JsxRuntime.jsxs("div", {
                                                      children: [
                                                        JsxRuntime.jsx(LucideReact.Crown, {
                                                              size: 13,
                                                              strokeWidth: 2.5,
                                                              fill: "currentColor"
                                                            }),
                                                        JsxRuntime.jsx("span", {
                                                              children: d.toFixed(1),
                                                              className: "font-mono text-xs font-bold"
                                                            })
                                                      ],
                                                      className: "flex items-center gap-1 text-[#64851d] dark:text-[#bdf25d]"
                                                    });
                                        })), JsxRuntime.jsx("span", {
                                        children: "—",
                                        className: "font-mono text-xs text-gray-300 dark:text-gray-600"
                                      })),
                              className: "relative w-16 hidden md:flex justify-end items-center"
                            }),
                        JsxRuntime.jsx(LangProvider.Router.Link.make, {
                              to: "./p/" + props.userId,
                              children: JsxRuntime.jsx("span", {
                                    children: t`View my profile`,
                                    className: "sr-only"
                                  }),
                              className: "absolute inset-0 z-10"
                            })
                      ],
                      className: "group relative flex items-center overflow-hidden rounded-xl border border-[#a3d949]/70 bg-white px-3 py-3.5 shadow-[0_8px_24px_rgba(82,112,17,0.14)] ring-1 ring-[#bdf25d]/20 transition-shadow hover:shadow-[0_8px_28px_rgba(82,112,17,0.24)] md:px-4 md:py-5 dark:border-[#bdf25d]/35 dark:bg-[#1e1f23] dark:shadow-[0_8px_28px_rgba(0,0,0,0.32)]"
                    })
              ],
              className: "mb-4"
            });
}

var CurrentUserStanding = {
  make: RatingList$CurrentUserStanding
};

function RatingList(props) {
  var viewerPicture = props.viewerPicture;
  var viewerName = props.viewerName;
  var viewerDays = props.viewerDays;
  var viewerOrdinal = props.viewerOrdinal;
  var viewerUserId = props.viewerUserId;
  var __showDraftUi = props.showDraftUi;
  var __search = props.search;
  var __genderFilter = props.genderFilter;
  var genderFilter = __genderFilter !== undefined ? __genderFilter : "all";
  var search = __search !== undefined ? __search : "";
  var showDraftUi = __showDraftUi !== undefined ? __showDraftUi : false;
  ReactExperimental.useTransition();
  var match = usePagination(props.ratings);
  var isLoadingNext = match.isLoadingNext;
  var hasNext = match.hasNext;
  var loadNext = match.loadNext;
  var data = match.data;
  var match$1 = ReactRouterDom.useSearchParams();
  var loadedWithBefore = Core__Option.isSome(Router.SearchParams.get(match$1[0], "before"));
  var allRatings = getConnectionNodes(data.ratings);
  var pageInfo = data.ratings.pageInfo;
  var hasPrevious = pageInfo.hasPreviousPage;
  var sentinelRef = React.useRef(null);
  var loadMoreInPlace = function () {
    var endCursor = pageInfo.endCursor;
    if (endCursor !== undefined) {
      window.history.replaceState(null, "", "?after=" + encodeURIComponent(endCursor));
    }
    loadNext(20, undefined);
  };
  var dict = {};
  var maleCount = {
    contents: 0
  };
  var femaleCount = {
    contents: 0
  };
  allRatings.forEach(function (node) {
        var match = Core__Option.flatMap(node.user, (function (u) {
                return u.gender;
              }));
        if (match !== undefined && (match === "female" || match === "male") && match === "female") {
          femaleCount.contents = femaleCount.contents + 1 | 0;
          dict[node.id] = femaleCount.contents;
          return ;
        }
        maleCount.contents = maleCount.contents + 1 | 0;
        dict[node.id] = maleCount.contents;
      });
  var searchQuery = search.trim().toLowerCase();
  var filtered = allRatings.map(function (node, index) {
          return [
                  node,
                  index + 1 | 0
                ];
        }).filter(function (param) {
        var node = param[0];
        var notViewer = viewerUserId !== undefined ? Caml_obj.notequal(Core__Option.map(node.user, (function (u) {
                      return u.id;
                    })), viewerUserId) : true;
        var genderOk = genderFilter === "all" ? true : (
            genderFilter === "female" ? Caml_obj.equal(Core__Option.flatMap(node.user, (function (u) {
                          return u.gender;
                        })), "female") : Caml_obj.notequal(Core__Option.flatMap(node.user, (function (u) {
                          return u.gender;
                        })), "female")
          );
        var searchOk = searchQuery === "" || Core__Option.getOr(Core__Option.map(Core__Option.flatMap(node.user, (function (u) {
                        return u.lineUsername;
                      })), (function (name) {
                    return name.toLowerCase().includes(searchQuery);
                  })), false);
        if (notViewer && genderOk) {
          return searchOk;
        } else {
          return false;
        }
      });
  var connOrdinals = Core__Array.filterMap(allRatings, (function (node) {
          return node.ordinal;
        }));
  var first = connOrdinals[0];
  var connMax = first !== undefined ? Core__Array.reduce(connOrdinals, first, (function (acc, next) {
            if (next > acc) {
              return next;
            } else {
              return acc;
            }
          })) : 0;
  var connMin = Core__Array.reduce(connOrdinals, connMax, (function (acc, next) {
          if (next < acc) {
            return next;
          } else {
            return acc;
          }
        }));
  var viewerDupr = Core__Option.map(props.viewerMu, (function (mu) {
          return Rating.guessDupr(mu).toFixed(2);
        }));
  var viewerStanding;
  if (viewerUserId !== undefined && viewerOrdinal !== undefined) {
    var rank = 1 + allRatings.filter(function (node) {
          return Core__Option.getOr(node.ordinal, 0) > viewerOrdinal;
        }).length | 0;
    var progress = connMax === connMin ? 100 : (viewerOrdinal - connMin) / (connMax - connMin) * 100;
    viewerStanding = [
      viewerUserId,
      rank,
      viewerOrdinal,
      viewerDupr,
      progress
    ];
  } else {
    viewerStanding = undefined;
  }
  var ordinals = Core__Array.filterMap(filtered, (function (param) {
          return param[0].ordinal;
        }));
  var first$1 = ordinals[0];
  var maxRating = first$1 !== undefined ? Core__Array.reduce(ordinals, first$1, (function (acc, next) {
            if (next > acc) {
              return next;
            } else {
              return acc;
            }
          })) : 0;
  var minRating = Core__Array.reduce(ordinals, maxRating, (function (acc, next) {
          if (next < acc) {
            return next;
          } else {
            return acc;
          }
        }));
  var singleGender = genderFilter === "male" || genderFilter === "female";
  var isFiltered = singleGender || searchQuery !== "";
  var draftEnabled = showDraftUi && !hasPrevious;
  var canAutoLoad = hasNext && !isLoadingNext && !loadedWithBefore;
  React.useEffect((function () {
          if (!canAutoLoad) {
            return ;
          }
          var el = sentinelRef.current;
          if (el == null) {
            return ;
          }
          var observer = new IntersectionObserver((function (entries) {
                  var entry = entries[0];
                  if (entry !== undefined && entry.isIntersecting) {
                    return loadMoreInPlace();
                  }
                  
                }), {
                rootMargin: "0px 0px 320px 0px",
                threshold: 0.01
              });
          observer.observe(el);
          return (function () {
                    observer.disconnect();
                  });
        }), [
        canAutoLoad,
        allRatings.length
      ]);
  var tmp;
  if (isLoadingNext) {
    tmp = JsxRuntime.jsxs("div", {
          children: [
            JsxRuntime.jsx(LucideReact.Loader2, {
                  size: 18,
                  className: "animate-spin text-[#65a30d] dark:text-[#bdf25d]"
                }),
            JsxRuntime.jsx("span", {
                  children: t`Loading next standings`,
                  className: "font-mono text-[11px] font-bold uppercase tracking-wider text-gray-600 dark:text-gray-300"
                })
          ],
          className: "flex items-center justify-center gap-3 rounded-xl border border-gray-200 bg-white px-4 py-4 mt-3 mb-8 shadow-sm dark:border-[#2a2b30] dark:bg-[#1e1f23]"
        });
  } else if (hasNext) {
    var loadMoreStyle = "flex w-full items-center justify-center gap-2 rounded-xl border border-dashed border-gray-300 px-4 py-4 mt-3 mb-8 font-mono text-[10px] font-bold uppercase tracking-widest text-gray-400 transition-colors hover:border-[#a3d949] hover:text-[#4d6f12] dark:border-[#3a3b40] dark:text-gray-500 dark:hover:border-[#bdf25d]/60 dark:hover:text-[#bdf25d]";
    var loadMoreLabel = JsxRuntime.jsxs(JsxRuntime.Fragment, {
          children: [
            JsxRuntime.jsxs("span", {
                  children: [
                    JsxRuntime.jsx("span", {
                          className: "h-1 w-1 rounded-full bg-current"
                        }),
                    JsxRuntime.jsx("span", {
                          className: "h-1 w-1 rounded-full bg-current"
                        }),
                    JsxRuntime.jsx("span", {
                          className: "h-1 w-1 rounded-full bg-current"
                        })
                  ],
                  className: "flex gap-1"
                }),
            t`Load more players...`
          ]
        });
    tmp = loadedWithBefore ? Core__Option.getOr(Core__Option.map(pageInfo.endCursor, (function (endCursor) {
                  return JsxRuntime.jsx(LangProvider.Router.Link.make, {
                              to: "./?after=" + encodeURIComponent(endCursor),
                              children: loadMoreLabel,
                              className: loadMoreStyle
                            });
                })), null) : JsxRuntime.jsx("button", {
            children: loadMoreLabel,
            className: loadMoreStyle,
            type: "button",
            onClick: (function (param) {
                loadMoreInPlace();
              })
          });
  } else {
    tmp = null;
  }
  return JsxRuntime.jsx(Layout.Container.make, {
              children: JsxRuntime.jsxs(JsxRuntime.Fragment, {
                    children: [
                      hasPrevious ? Core__Option.getOr(Core__Option.map(pageInfo.startCursor, (function (startCursor) {
                                    return JsxRuntime.jsx(LangProvider.Router.Link.make, {
                                                to: "./?before=" + encodeURIComponent(startCursor),
                                                children: t`...load higher rated players`,
                                                className: "flex w-full items-center justify-center gap-2 rounded-xl border border-dashed border-gray-300 px-4 py-3 mb-3 font-mono text-[10px] font-bold uppercase tracking-widest text-gray-400 transition-colors hover:border-[#a3d949] hover:text-[#4d6f12] dark:border-[#3a3b40] dark:text-gray-500 dark:hover:border-[#bdf25d]/60 dark:hover:text-[#bdf25d]"
                                              });
                                  })), null) : null,
                      Core__Option.getOr(Core__Option.map(viewerStanding, (function (param) {
                                  return JsxRuntime.jsx(RatingList$CurrentUserStanding, {
                                              rank: param[1],
                                              ordinal: param[2],
                                              dupr: param[3],
                                              days: viewerDays,
                                              progress: param[4],
                                              name: Core__Option.getOr(viewerName, "You"),
                                              picture: viewerPicture,
                                              userId: param[0]
                                            });
                                })), null),
                      filtered.length > 0 ? JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx("div", {
                                      children: "#",
                                      className: "w-10 md:w-14 text-center"
                                    }),
                                JsxRuntime.jsx("div", {
                                      children: t`Player`,
                                      className: "flex-1 ml-2"
                                    }),
                                JsxRuntime.jsx("div", {
                                      children: t`Rating`,
                                      className: "w-24 md:w-32 text-right"
                                    }),
                                JsxRuntime.jsx("div", {
                                      children: t`Est. DUPR`,
                                      className: "w-20 text-right hidden sm:block"
                                    }),
                                JsxRuntime.jsx("div", {
                                      children: t`Days #1`,
                                      className: "w-16 text-right hidden md:block"
                                    })
                              ],
                              className: "flex items-center px-4 py-2 text-[10px] font-black font-mono text-gray-400 dark:text-gray-500 tracking-widest uppercase mb-2"
                            }) : null,
                      JsxRuntime.jsx("ul", {
                            children: filtered.map(function (param) {
                                  var node = param[0];
                                  var genderRank = dict[node.id];
                                  var showCutoff = draftEnabled && singleGender && searchQuery === "" && Caml_obj.equal(genderRank, 8);
                                  return JsxRuntime.jsxs(React.Fragment, {
                                              children: [
                                                JsxRuntime.jsx(RatingList$RatingItem, {
                                                      rating: node.fragmentRefs,
                                                      rank: param[1],
                                                      genderRank: genderRank,
                                                      maxRating: maxRating,
                                                      minRating: minRating,
                                                      draftEnabled: draftEnabled
                                                    }),
                                                showCutoff ? JsxRuntime.jsxs("li", {
                                                        children: [
                                                          JsxRuntime.jsx("div", {
                                                                className: "h-px flex-1 bg-gradient-to-r from-transparent to-amber-400/60"
                                                              }),
                                                          JsxRuntime.jsxs("span", {
                                                                children: [
                                                                  JsxRuntime.jsx(LucideReact.Award, {
                                                                        size: 12,
                                                                        strokeWidth: 2.5
                                                                      }),
                                                                  t`Draft cutoff · Top 8 qualify`
                                                                ],
                                                                className: "flex items-center gap-1.5 font-mono text-[10px] font-black uppercase tracking-widest text-amber-600 dark:text-amber-400 whitespace-nowrap"
                                                              }),
                                                          JsxRuntime.jsx("div", {
                                                                className: "h-px flex-1 bg-gradient-to-l from-transparent to-amber-400/60"
                                                              })
                                                        ],
                                                        className: "relative flex items-center gap-2 py-2 px-3 my-1"
                                                      }) : null
                                              ]
                                            }, node.id);
                                }),
                            className: "flex flex-col gap-0 pb-2",
                            role: "list"
                          }),
                      filtered.length === 0 ? JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx(LucideReact.Users, {
                                      size: 24,
                                      className: "mx-auto mb-3 text-gray-300 dark:text-gray-600"
                                    }),
                                JsxRuntime.jsx("p", {
                                      children: t`No players found`,
                                      className: "font-mono text-sm font-bold uppercase tracking-widest text-gray-500 dark:text-gray-400"
                                    }),
                                isFiltered ? JsxRuntime.jsx("p", {
                                        children: t`Try broadening your search or filters.`,
                                        className: "mt-1 text-xs text-gray-400 dark:text-gray-500"
                                      }) : null
                              ],
                              className: "rounded-xl border border-gray-200 bg-white py-12 text-center dark:border-[#2a2b30] dark:bg-[#1e1f23]"
                            }) : null,
                      JsxRuntime.jsxs("div", {
                            children: [
                              tmp,
                              !hasNext && filtered.length > 0 ? JsxRuntime.jsxs("div", {
                                      children: [
                                        JsxRuntime.jsx(LucideReact.CheckCircle2, {
                                              size: 14,
                                              className: "text-[#65a30d] dark:text-[#bdf25d]"
                                            }),
                                        t`All players loaded`
                                      ],
                                      className: "flex items-center justify-center gap-2 py-4 mb-4 font-mono text-[10px] font-bold uppercase tracking-widest text-gray-400 dark:text-gray-500"
                                    }) : null
                            ],
                            ref: Caml_option.some(sentinelRef)
                          })
                    ]
                  }),
              className: "mt-4"
            });
}

var draftSize = 8;

var make = RatingList;

var $$default = RatingList;

export {
  Fragment ,
  ItemFragment ,
  $$IntersectionObserver ,
  draftSize ,
  initialsOf ,
  RatingItem ,
  CurrentUserStanding ,
  make ,
  $$default as default,
}
/*  Not a pure module */
