// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as PlayerRow from "../molecules/PlayerRow.re.mjs";
import * as Core__Array from "@rescript/core/src/Core__Array.re.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.re.mjs";
import * as LucideReact from "lucide-react";
import * as JsxRuntime from "react/jsx-runtime";

import { t } from '@lingui/macro'
;

function ScoreModal(props) {
  var getUserFragmentRefs = props.getUserFragmentRefs;
  var onClose = props.onClose;
  var onSubmit = props.onSubmit;
  var winningTeam = props.winningTeam;
  var match = props.match;
  var match$1 = React.useState(function () {
        
      });
  var setTeam1Score = match$1[1];
  var team1Score = match$1[0];
  var match$2 = React.useState(function () {
        
      });
  var team2 = match[1];
  var team1 = match[0];
  var setTeam2Score = match$2[1];
  var team2Score = match$2[0];
  var match$3;
  match$3 = winningTeam === "Team1" ? [
      team1,
      team2
    ] : [
      team2,
      team1
    ];
  var winningScore;
  winningScore = winningTeam === "Team1" ? team1Score : team2Score;
  var losingScore;
  losingScore = winningTeam === "Team1" ? team2Score : team1Score;
  var handleSubmit = function () {
    if (team1Score !== undefined && team2Score !== undefined) {
      onSubmit(team1Score, team2Score);
      return onClose();
    }
    
  };
  var handleNoScore = function () {
    if (winningTeam === "Team1") {
      onSubmit(1, -1);
    } else {
      onSubmit(-1, 1);
    }
    onClose();
  };
  var canSubmit = Core__Option.isSome(team1Score) && Core__Option.isSome(team2Score);
  var numbers = Core__Array.fromInitializer(31, (function (i) {
          return i;
        }));
  var winningTeamNumber;
  winningTeamNumber = winningTeam === "Team1" ? 1 : 2;
  var losingTeamNumber;
  losingTeamNumber = winningTeam === "Team1" ? 2 : 1;
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsxs("div", {
                    children: [
                      JsxRuntime.jsxs("div", {
                            children: [
                              JsxRuntime.jsxs("div", {
                                    children: [
                                      JsxRuntime.jsx(LucideReact.Trophy, {
                                            className: "w-6 h-6 text-yellow-500"
                                          }),
                                      JsxRuntime.jsx("h2", {
                                            children: t`Enter Match Score`,
                                            className: "text-xl font-bold text-slate-800"
                                          })
                                    ],
                                    className: "flex items-center gap-3"
                                  }),
                              JsxRuntime.jsx("button", {
                                    children: JsxRuntime.jsx(LucideReact.X, {
                                          className: "w-5 h-5 text-slate-600"
                                        }),
                                    "aria-label": "Close",
                                    className: "p-2 hover:bg-slate-100 rounded-lg transition-colors",
                                    onClick: (function (param) {
                                        onClose();
                                      })
                                  })
                            ],
                            className: "sticky top-0 bg-white border-b border-slate-200 px-6 py-4 flex items-center justify-between"
                          }),
                      JsxRuntime.jsxs("div", {
                            children: [
                              JsxRuntime.jsxs("div", {
                                    children: [
                                      JsxRuntime.jsxs("div", {
                                            children: [
                                              JsxRuntime.jsx(LucideReact.Trophy, {
                                                    className: "w-5 h-5 text-yellow-500 fill-yellow-500"
                                                  }),
                                              JsxRuntime.jsx("h3", {
                                                    children: t`Winning Team (Team ${winningTeamNumber.toString()})`,
                                                    className: "text-lg font-bold text-green-700"
                                                  })
                                            ],
                                            className: "flex items-center gap-2"
                                          }),
                                      JsxRuntime.jsx("div", {
                                            children: match$3[0].map(function (player) {
                                                  return JsxRuntime.jsx(PlayerRow.make, {
                                                              player: player,
                                                              isEditing: false,
                                                              teamSide: "Left",
                                                              skillLevel: 0,
                                                              getUserFragmentRefs: getUserFragmentRefs
                                                            }, player.id);
                                                }),
                                            className: "flex items-center gap-2 mb-2"
                                          }),
                                      JsxRuntime.jsx("div", {
                                            children: JsxRuntime.jsx("div", {
                                                  children: JsxRuntime.jsx("span", {
                                                        children: Core__Option.getOr(Core__Option.map(winningScore, (function (s) {
                                                                    return s.toString();
                                                                  })), "—"),
                                                        className: "text-3xl font-bold text-green-700"
                                                      }),
                                                  className: "inline-block px-4 py-2 bg-green-100 rounded-lg"
                                                }),
                                            className: "text-center mb-2"
                                          }),
                                      JsxRuntime.jsx("div", {
                                            children: numbers.map(function (num) {
                                                  var isSelected = Core__Option.getOr(Core__Option.map(winningScore, (function (s) {
                                                              return s === num;
                                                            })), false);
                                                  return JsxRuntime.jsx("button", {
                                                              children: num.toString(),
                                                              className: isSelected ? "h-12 flex items-center justify-center text-base font-bold transition-all border-r border-b border-slate-200 bg-green-600 text-white" : "h-12 flex items-center justify-center text-base font-bold transition-all border-r border-b border-slate-200 bg-white text-slate-700 hover:bg-slate-100 active:bg-slate-200",
                                                              onClick: (function (param) {
                                                                  if (winningTeam === "Team1") {
                                                                    return setTeam1Score(function (param) {
                                                                                return num;
                                                                              });
                                                                  } else {
                                                                    return setTeam2Score(function (param) {
                                                                                return num;
                                                                              });
                                                                  }
                                                                })
                                                            }, num.toString());
                                                }),
                                            className: "grid grid-cols-8 gap-0 border border-slate-300 overflow-hidden rounded-lg"
                                          })
                                    ],
                                    className: "space-y-3"
                                  }),
                              JsxRuntime.jsxs("div", {
                                    children: [
                                      JsxRuntime.jsx("h3", {
                                            children: t`Losing Team (Team ${losingTeamNumber.toString()})`,
                                            className: "text-lg font-bold text-slate-600"
                                          }),
                                      JsxRuntime.jsx("div", {
                                            children: match$3[1].map(function (player) {
                                                  return JsxRuntime.jsx(PlayerRow.make, {
                                                              player: player,
                                                              isEditing: false,
                                                              teamSide: "Left",
                                                              skillLevel: 0,
                                                              getUserFragmentRefs: getUserFragmentRefs
                                                            }, player.id);
                                                }),
                                            className: "flex items-center gap-2 mb-2"
                                          }),
                                      JsxRuntime.jsx("div", {
                                            children: JsxRuntime.jsx("div", {
                                                  children: JsxRuntime.jsx("span", {
                                                        children: Core__Option.getOr(Core__Option.map(losingScore, (function (s) {
                                                                    return s.toString();
                                                                  })), "—"),
                                                        className: "text-3xl font-bold text-slate-700"
                                                      }),
                                                  className: "inline-block px-4 py-2 bg-slate-100 rounded-lg"
                                                }),
                                            className: "text-center mb-2"
                                          }),
                                      JsxRuntime.jsx("div", {
                                            children: numbers.map(function (num) {
                                                  var isDisabled = Core__Option.getOr(Core__Option.map(winningScore, (function (ws) {
                                                              return num >= ws;
                                                            })), false);
                                                  var isSelected = Core__Option.getOr(Core__Option.map(losingScore, (function (s) {
                                                              return s === num;
                                                            })), false);
                                                  return JsxRuntime.jsx("button", {
                                                              children: num.toString(),
                                                              className: isDisabled ? "h-12 flex items-center justify-center text-base font-bold transition-all border-r border-b border-slate-200 bg-slate-50 text-slate-300 cursor-not-allowed" : (
                                                                  isSelected ? "h-12 flex items-center justify-center text-base font-bold transition-all border-r border-b border-slate-200 bg-slate-600 text-white" : "h-12 flex items-center justify-center text-base font-bold transition-all border-r border-b border-slate-200 bg-white text-slate-700 hover:bg-slate-100 active:bg-slate-200"
                                                                ),
                                                              disabled: isDisabled,
                                                              onClick: (function (param) {
                                                                  if (isDisabled) {
                                                                    return ;
                                                                  } else if (winningTeam === "Team1") {
                                                                    return setTeam2Score(function (param) {
                                                                                return num;
                                                                              });
                                                                  } else {
                                                                    return setTeam1Score(function (param) {
                                                                                return num;
                                                                              });
                                                                  }
                                                                })
                                                            }, num.toString());
                                                }),
                                            className: "grid grid-cols-8 gap-0 border border-slate-300 overflow-hidden rounded-lg"
                                          })
                                    ],
                                    className: "space-y-3"
                                  })
                            ],
                            className: "p-6 space-y-6"
                          }),
                      JsxRuntime.jsxs("div", {
                            children: [
                              JsxRuntime.jsxs("button", {
                                    children: [
                                      JsxRuntime.jsx(LucideReact.MinusCircle, {
                                            className: "w-4 h-4"
                                          }),
                                      t`No Score`
                                    ],
                                    className: "px-4 py-2 rounded-lg font-medium bg-amber-100 text-amber-900 hover:bg-amber-200 transition-colors flex items-center gap-2",
                                    onClick: (function (param) {
                                        handleNoScore();
                                      })
                                  }),
                              JsxRuntime.jsx("button", {
                                    children: t`Save Score`,
                                    className: canSubmit ? "px-6 py-2 rounded-lg font-medium transition-colors bg-blue-600 text-white hover:bg-blue-700 shadow-md" : "px-6 py-2 rounded-lg font-medium transition-colors bg-slate-300 text-slate-500 cursor-not-allowed",
                                    disabled: !canSubmit,
                                    onClick: (function (param) {
                                        handleSubmit();
                                      })
                                  })
                            ],
                            className: "sticky bottom-0 bg-slate-50 border-t border-slate-200 px-6 py-4 flex items-center justify-end gap-3"
                          })
                    ],
                    className: "select-none bg-white rounded-xl shadow-2xl max-w-2xl w-full max-h-[90vh] overflow-y-auto"
                  }),
              className: "fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4"
            });
}

var make = ScoreModal;

export {
  make ,
}
/*  Not a pure module */
