// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as PlayerRow from "../molecules/PlayerRow.re.mjs";
import * as Core__Array from "@rescript/core/src/Core__Array.re.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.re.mjs";
import * as LucideReact from "lucide-react";
import * as JsxRuntime from "react/jsx-runtime";

import { t } from '@lingui/macro'
;

var playerRowDark = "dark:[&_span.text-slate-800]:text-gray-100 dark:[&_span.text-slate-600]:text-gray-300 dark:[&_span.text-pink-700]:text-pink-300 dark:[&_span.text-pink-600]:text-pink-400 dark:[&_.text-slate-500]:text-gray-400";

function ScoreModal(props) {
  var getUserFragmentRefs = props.getUserFragmentRefs;
  var onClose = props.onClose;
  var onSubmit = props.onSubmit;
  var winningTeam = props.winningTeam;
  var match = props.match;
  var match$1 = React.useState(function () {
        
      });
  var setTeam1Score = match$1[1];
  var team1Score = match$1[0];
  var match$2 = React.useState(function () {
        
      });
  var team2 = match[1];
  var team1 = match[0];
  var setTeam2Score = match$2[1];
  var team2Score = match$2[0];
  var match$3;
  match$3 = winningTeam === "Team1" ? [
      team1,
      team2
    ] : [
      team2,
      team1
    ];
  var winningScore;
  winningScore = winningTeam === "Team1" ? team1Score : team2Score;
  var losingScore;
  losingScore = winningTeam === "Team1" ? team2Score : team1Score;
  var handleSubmit = function () {
    if (team1Score !== undefined && team2Score !== undefined) {
      onSubmit(team1Score, team2Score);
      return onClose();
    }
    
  };
  var handleNoScore = function () {
    if (winningTeam === "Team1") {
      onSubmit(1, -1);
    } else {
      onSubmit(-1, 1);
    }
    onClose();
  };
  var canSubmit = Core__Option.isSome(team1Score) && Core__Option.isSome(team2Score);
  var isDraw = winningScore !== undefined && losingScore !== undefined ? winningScore === losingScore : false;
  var numbers = Core__Array.fromInitializer(31, (function (i) {
          return i;
        }));
  var winningTeamNumber;
  winningTeamNumber = winningTeam === "Team1" ? 1 : 2;
  var losingTeamNumber;
  losingTeamNumber = winningTeam === "Team1" ? 2 : 1;
  var teamHeading = function (teamNumber, isWinningSide) {
    return JsxRuntime.jsxs("div", {
                children: [
                  isDraw ? JsxRuntime.jsx(LucideReact.Equal, {
                          className: "w-5 h-5 text-amber-600 dark:text-amber-400"
                        }) : (
                      isWinningSide ? JsxRuntime.jsx(LucideReact.Trophy, {
                              className: "w-5 h-5 text-yellow-500 fill-yellow-500"
                            }) : null
                    ),
                  JsxRuntime.jsx("h3", {
                        children: isDraw ? t`Team ${teamNumber.toString()}` : (
                            isWinningSide ? t`Winning Team (Team ${teamNumber.toString()})` : t`Losing Team (Team ${teamNumber.toString()})`
                          ),
                        className: isDraw ? "text-lg font-bold text-slate-700 dark:text-gray-200" : (
                            isWinningSide ? "text-lg font-bold text-green-700 dark:text-green-400" : "text-lg font-bold text-slate-600 dark:text-gray-300"
                          )
                      })
                ],
                className: "flex items-center gap-2"
              });
  };
  var match$4 = isDraw ? [
      "bg-slate-100 dark:bg-[#2a2b30]",
      "text-slate-700 dark:text-gray-200",
      "bg-slate-600"
    ] : [
      "bg-green-100 dark:bg-green-900/30",
      "text-green-700 dark:text-green-400",
      "bg-green-600"
    ];
  var accentSelected = match$4[2];
  var numberButtonBase = "h-12 flex items-center justify-center text-base font-bold transition-all border-r border-b border-slate-200 dark:border-[#2a2b30]";
  var numberButtonIdle = numberButtonBase + " bg-white text-slate-700 hover:bg-slate-100 active:bg-slate-200 dark:bg-[#1e1f23] dark:text-gray-200 dark:hover:bg-[#2a2b30] dark:active:bg-[#3a3b40]";
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsxs("div", {
                    children: [
                      JsxRuntime.jsxs("div", {
                            children: [
                              JsxRuntime.jsxs("div", {
                                    children: [
                                      isDraw ? JsxRuntime.jsx(LucideReact.Equal, {
                                              className: "w-6 h-6 text-amber-600 dark:text-amber-400"
                                            }) : JsxRuntime.jsx(LucideReact.Trophy, {
                                              className: "w-6 h-6 text-yellow-500"
                                            }),
                                      JsxRuntime.jsx("h2", {
                                            children: t`Enter Match Score`,
                                            className: "text-xl font-bold text-slate-800 dark:text-gray-100"
                                          })
                                    ],
                                    className: "flex items-center gap-3"
                                  }),
                              JsxRuntime.jsx("button", {
                                    children: JsxRuntime.jsx(LucideReact.X, {
                                          className: "w-5 h-5 text-slate-600 dark:text-gray-400"
                                        }),
                                    "aria-label": "Close",
                                    className: "p-2 hover:bg-slate-100 dark:hover:bg-[#2a2b30] rounded-lg transition-colors",
                                    onClick: (function (param) {
                                        onClose();
                                      })
                                  })
                            ],
                            className: "sticky top-0 bg-white dark:bg-[#1e1f23] border-b border-slate-200 dark:border-[#2a2b30] px-6 py-4 flex items-center justify-between"
                          }),
                      JsxRuntime.jsxs("div", {
                            children: [
                              JsxRuntime.jsxs("div", {
                                    children: [
                                      teamHeading(winningTeamNumber, true),
                                      JsxRuntime.jsx("div", {
                                            children: match$3[0].map(function (player) {
                                                  return JsxRuntime.jsx(PlayerRow.make, {
                                                              player: player,
                                                              isEditing: false,
                                                              teamSide: "Left",
                                                              skillLevel: 0,
                                                              getUserFragmentRefs: getUserFragmentRefs
                                                            }, player.id);
                                                }),
                                            className: "flex items-center gap-2 mb-2"
                                          }),
                                      JsxRuntime.jsx("div", {
                                            children: JsxRuntime.jsx("div", {
                                                  children: JsxRuntime.jsx("span", {
                                                        children: Core__Option.getOr(Core__Option.map(winningScore, (function (s) {
                                                                    return s.toString();
                                                                  })), "—"),
                                                        className: "text-3xl font-bold " + match$4[1]
                                                      }),
                                                  className: "inline-block px-4 py-2 " + match$4[0] + " rounded-lg"
                                                }),
                                            className: "text-center mb-2"
                                          }),
                                      JsxRuntime.jsx("div", {
                                            children: numbers.map(function (num) {
                                                  var isSelected = Core__Option.getOr(Core__Option.map(winningScore, (function (s) {
                                                              return s === num;
                                                            })), false);
                                                  return JsxRuntime.jsx("button", {
                                                              children: num.toString(),
                                                              className: isSelected ? numberButtonBase + " " + accentSelected + " text-white" : numberButtonIdle,
                                                              onClick: (function (param) {
                                                                  if (winningTeam === "Team1") {
                                                                    return setTeam1Score(function (param) {
                                                                                return num;
                                                                              });
                                                                  } else {
                                                                    return setTeam2Score(function (param) {
                                                                                return num;
                                                                              });
                                                                  }
                                                                })
                                                            }, num.toString());
                                                }),
                                            className: "grid grid-cols-8 gap-0 border border-slate-300 dark:border-[#3a3b40] overflow-hidden rounded-lg"
                                          })
                                    ],
                                    className: "space-y-3"
                                  }),
                              JsxRuntime.jsxs("div", {
                                    children: [
                                      teamHeading(losingTeamNumber, false),
                                      JsxRuntime.jsx("div", {
                                            children: match$3[1].map(function (player) {
                                                  return JsxRuntime.jsx(PlayerRow.make, {
                                                              player: player,
                                                              isEditing: false,
                                                              teamSide: "Left",
                                                              skillLevel: 0,
                                                              getUserFragmentRefs: getUserFragmentRefs
                                                            }, player.id);
                                                }),
                                            className: "flex items-center gap-2 mb-2"
                                          }),
                                      JsxRuntime.jsx("div", {
                                            children: JsxRuntime.jsx("div", {
                                                  children: JsxRuntime.jsx("span", {
                                                        children: Core__Option.getOr(Core__Option.map(losingScore, (function (s) {
                                                                    return s.toString();
                                                                  })), "—"),
                                                        className: "text-3xl font-bold text-slate-700 dark:text-gray-200"
                                                      }),
                                                  className: "inline-block px-4 py-2 bg-slate-100 dark:bg-[#2a2b30] rounded-lg"
                                                }),
                                            className: "text-center mb-2"
                                          }),
                                      JsxRuntime.jsx("div", {
                                            children: numbers.map(function (num) {
                                                  var isDisabled = Core__Option.getOr(Core__Option.map(winningScore, (function (ws) {
                                                              return num > ws;
                                                            })), false);
                                                  var isSelected = Core__Option.getOr(Core__Option.map(losingScore, (function (s) {
                                                              return s === num;
                                                            })), false);
                                                  return JsxRuntime.jsx("button", {
                                                              children: num.toString(),
                                                              className: isDisabled ? numberButtonBase + " bg-slate-50 text-slate-300 dark:bg-[#1a1a1e] dark:text-gray-600 cursor-not-allowed" : (
                                                                  isSelected ? numberButtonBase + " bg-slate-600 text-white" : numberButtonIdle
                                                                ),
                                                              disabled: isDisabled,
                                                              onClick: (function (param) {
                                                                  if (isDisabled) {
                                                                    return ;
                                                                  } else if (winningTeam === "Team1") {
                                                                    return setTeam2Score(function (param) {
                                                                                return num;
                                                                              });
                                                                  } else {
                                                                    return setTeam1Score(function (param) {
                                                                                return num;
                                                                              });
                                                                  }
                                                                })
                                                            }, num.toString());
                                                }),
                                            className: "grid grid-cols-8 gap-0 border border-slate-300 dark:border-[#3a3b40] overflow-hidden rounded-lg"
                                          })
                                    ],
                                    className: "space-y-3"
                                  })
                            ],
                            className: "p-6 space-y-6 " + playerRowDark
                          }),
                      JsxRuntime.jsxs("div", {
                            children: [
                              isDraw ? JsxRuntime.jsxs("span", {
                                      children: [
                                        JsxRuntime.jsx(LucideReact.Equal, {
                                              className: "w-4 h-4"
                                            }),
                                        t`Equal scores — this will be recorded as a draw`
                                      ],
                                      className: "mr-auto flex items-center gap-1.5 text-sm font-medium text-amber-700 dark:text-amber-400"
                                    }) : null,
                              JsxRuntime.jsxs("button", {
                                    children: [
                                      JsxRuntime.jsx(LucideReact.MinusCircle, {
                                            className: "w-4 h-4"
                                          }),
                                      t`No Score`
                                    ],
                                    className: "px-4 py-2 rounded-lg font-medium bg-amber-100 text-amber-900 hover:bg-amber-200 dark:bg-amber-900/30 dark:text-amber-300 dark:hover:bg-amber-900/50 transition-colors flex items-center gap-2",
                                    onClick: (function (param) {
                                        handleNoScore();
                                      })
                                  }),
                              JsxRuntime.jsx("button", {
                                    children: t`Save Score`,
                                    className: canSubmit ? "px-6 py-2 rounded-lg font-medium transition-colors bg-blue-600 text-white hover:bg-blue-700 shadow-md" : "px-6 py-2 rounded-lg font-medium transition-colors bg-slate-300 text-slate-500 dark:bg-[#2a2b30] dark:text-gray-500 cursor-not-allowed",
                                    disabled: !canSubmit,
                                    onClick: (function (param) {
                                        handleSubmit();
                                      })
                                  })
                            ],
                            className: "sticky bottom-0 bg-slate-50 dark:bg-[#222326] border-t border-slate-200 dark:border-[#2a2b30] px-6 py-4 flex items-center justify-end gap-3"
                          })
                    ],
                    className: "select-none bg-white dark:bg-[#1e1f23] rounded-xl shadow-2xl max-w-2xl w-full max-h-[90vh] overflow-y-auto"
                  }),
              className: "fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4"
            });
}

var make = ScoreModal;

export {
  playerRowDark ,
  make ,
}
/*  Not a pure module */
