// Generated by ReScript, PLEASE EDIT WITH CARE


var CalendarClock = {};

var CalendarPlus = {};

var MapPin = {};

var CornerDownRight = {};

var Info = {};

var ArrowUpNarrowWide = {};

var ArrowUpWideNarrow = {};

var ArrowDownWideNarrow = {};

var MoveLeft = {};

var MoveRight = {};

var X = {};

var Settings = {};

var UserPlus = {};

var Clock = {};

var User = {};

var List = {};

var Calendar = {};

var Users = {};

var Check = {};

var ArrowUpCircle = {};

var Share = {};

var Pencil = {};

var Trophy = {};

var MessageCircle = {};

var Bell = {};

export {
  CalendarClock ,
  CalendarPlus ,
  MapPin ,
  CornerDownRight ,
  Info ,
  ArrowUpNarrowWide ,
  ArrowUpWideNarrow ,
  ArrowDownWideNarrow ,
  MoveLeft ,
  MoveRight ,
  X ,
  Settings ,
  UserPlus ,
  Clock ,
  User ,
  List ,
  Calendar ,
  Users ,
  Check ,
  ArrowUpCircle ,
  Share ,
  Pencil ,
  Trophy ,
  MessageCircle ,
  Bell ,
}
/* No side effect */
